// Command genhtmlentities turns the WHATWG's entities.json into the named
// character reference table in package html.
//
// The table is generated rather than typed because it has 2231 entries, and
// generated from the specification's own published file rather than from a copy
// of somebody's parser, so it is the authoritative list by construction.
//
// The standard publishes the file at one URL and keeps no versions of it, so
// the input is pinned by its SHA-256 — the Makefile's HTML_ENTITIES_SHA256 —
// which the fetch checks and this checks again, and the generated file records
// it. A file that has changed upstream is a failure that says so, and moving to
// it is a change to the pin:
//
//	make html-entities
//	go run ./cmd/genhtmlentities -source <url> -sha256 <hex> -in testdata/html/entities.json -out html/entities.go
//
// The output is committed; the input is not.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

type entity struct {
	Codepoints []rune `json:"codepoints"`
	Characters string `json:"characters"`
}

func main() {
	in := flag.String("in", "testdata/html/entities.json", "the WHATWG entities.json")
	out := flag.String("out", "html/entities.go", "the Go file to write")
	source := flag.String("source", "", "the URL the file was fetched from")
	pin := flag.String("sha256", "", "the SHA-256 the file is pinned to")
	flag.Parse()
	if *source == "" || *pin == "" {
		log.Fatal("no -source or -sha256: the table has to say which entities.json it is from")
	}

	raw, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("reading %s: %v (run `make html-entities`)", *in, err)
	}
	if sum := sha256.Sum256(raw); hex.EncodeToString(sum[:]) != *pin {
		log.Fatalf("%s has SHA-256 %x, and the table is pinned to %s: the standard's "+
			"file has changed, or this is not it", *in, sum, *pin)
	}
	var table map[string]entity
	if err := json.Unmarshal(raw, &table); err != nil {
		log.Fatalf("parsing %s: %v", *in, err)
	}
	if len(table) == 0 {
		log.Fatalf("%s holds no entities", *in)
	}

	names := make([]string, 0, len(table))
	longest := 0
	for name := range table {
		if !strings.HasPrefix(name, "&") {
			log.Fatalf("the entity %q does not begin with \"&\"", name)
		}
		// The key includes the "&"; the tokenizer matches what follows it.
		trimmed := name[1:]
		names = append(names, trimmed)
		if len(trimmed) > longest {
			longest = len(trimmed)
		}
	}
	sort.Strings(names)

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/genhtmlentities. DO NOT EDIT.
//
// Source: %s, SHA-256
// %s:
// the named character references of the HTML standard, %d of them.

package html

// maxEntityNameLen is the longest name in the table, which bounds how far the
// tokenizer looks ahead when matching one.
const maxEntityNameLen = %d

// namedEntities maps a character reference name — everything after the "&",
// including the ";" when the name has one — to the text it stands for.
//
// Names both with and without the trailing semicolon are present, because the
// standard keeps %d historical names that browsers still accept without it.
// Which of the two matched decides whether it was a parse error, so the
// distinction is kept rather than normalised away.
var namedEntities = map[string]string{
`, *source, *pin, len(table), longest, countLegacy(table))

	for _, name := range names {
		e := table["&"+name]
		fmt.Fprintf(&b, "\t%q: %q,\n", name, e.Characters)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("writing %s: %v", *out, err)
	}
	fmt.Printf("wrote %s: %d entities, longest name %d bytes\n", *out, len(table), longest)
}

func countLegacy(table map[string]entity) int {
	n := 0
	for name := range table {
		if !strings.HasSuffix(name, ";") {
			n++
		}
	}
	return n
}
