// Command genphrase generates the phrase segmentation model CSS Text §5.2's
// "auto-phrase" needs, from one of BudouX's.
//
// # Why a model and not a rule, and not a word list either
//
// §5.2's auto-phrase allows a line to end at a phrase boundary and nowhere
// else. A phrase is not a word: "東京へ" is one phrase and two words, and a
// value that broke between them would be doing what "normal" already does.
// Where one phrase ends and the next begins in "東京へ行きましょう。" is a fact
// about Japanese grammar, so — like the word lists cmd/gendict reads — the only
// way to know it is to have been told.
//
// A word list cannot be told it. Japanese is agglutinative and a phrase is a
// content word with its particles and inflections stuck to it, so a dictionary
// that had every word would still have to decide which of the boundaries
// between them are phrase boundaries and which are not. The decision is what
// the model is: BudouX scores each boundary from the characters around it,
// six either side as single characters, pairs and triples, and a positive total
// is a phrase boundary. It is a linear model with about sixteen hundred
// weights, which is why a language fits in twenty kilobytes where a word list
// takes two megabytes.
//
// # Where it comes from and what travels with it
//
// BudouX, which is what Chromium segments phrases with — so a page laid out
// from it breaks where a reader of the suite's references expects. Its own
// tests were written against that behaviour and name it: the suite's
// word-break-auto-phrase-001 asks for "東京へ" and "行きましょう。" and calls the
// decomposition "reasonable points", which is a test that can only be written
// about a model somebody has agreed on.
//
// The model is Apache-2.0 and the licence is copied into the generated file
// rather than summarised, for the reason cmd/gendict copies the Unicode one:
// the terms require that recipients get them, and a table with the terms
// stripped off is a table nobody may ship. There is no NOTICE file in the
// upstream repository, so there is nothing else to carry.
//
//	go run ./cmd/genphrase japanese <ja.json> <LICENSE> > paragraph/japanesephrases.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode/utf8"
)

// groups are BudouX's feature groups, in the order its parser reads them: the
// six single characters around a boundary, the three pairs, and the four
// triples. They are named here rather than taken from the file so that a model
// that grew a group would be a build failure and not a silently ignored
// feature.
var groups = [...]string{
	"UW1", "UW2", "UW3", "UW4", "UW5", "UW6",
	"BW1", "BW2", "BW3",
	"TW1", "TW2", "TW3", "TW4",
}

func main() {
	if len(os.Args) != 4 {
		fmt.Fprintln(os.Stderr, "usage: genphrase <name> <model.json> <LICENSE>")
		os.Exit(2)
	}
	name := os.Args[1]

	raw, err := os.ReadFile(os.Args[2])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var model map[string]map[string]int
	if err := json.Unmarshal(raw, &model); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	licence, err := os.ReadFile(os.Args[3])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	known := map[string]bool{}
	for _, g := range groups {
		known[g] = true
	}
	for g := range model {
		if !known[g] {
			fmt.Fprintf(os.Stderr, "genphrase: %s has a group this engine does not read: %s\n", os.Args[2], g)
			os.Exit(1)
		}
	}

	// The features, one per line, group first. Sorted within a group so that
	// the file can be compared with the one it came from and so that a reader
	// looking for a feature can find it; nothing about the scoring depends on
	// the order.
	var lines []string
	total, longest := 0, 0
	for _, g := range groups {
		keys := make([]string, 0, len(model[g]))
		for k := range model[g] {
			if k == "" || strings.ContainsAny(k, "\t\n\r`") {
				// A tab would be read as the field separator below and a
				// backquote could not go in the raw literal at all. No model
				// has either: a feature is characters of the text.
				fmt.Fprintf(os.Stderr, "genphrase: %s has a feature this format cannot hold: %q\n", g, k)
				os.Exit(1)
			}
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			lines = append(lines, fmt.Sprintf("%s\t%s\t%d", g, k, model[g][k]))
			total += model[g][k]
			if n := utf8.RuneCountInString(k); n > longest {
				longest = n
			}
		}
	}
	if len(lines) == 0 {
		fmt.Fprintln(os.Stderr, "genphrase: no features in the file")
		os.Exit(1)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/genphrase from BudouX's %s.\n// DO NOT EDIT.\n\npackage paragraph\n\n",
		os.Args[2][strings.LastIndexByte(os.Args[2], '/')+1:])
	fmt.Fprint(&b, "// The licence the model is under, copied from its own repository. See\n"+
		"// cmd/genphrase for why it is here in full rather than summarised.\n//\n")
	for _, line := range strings.Split(strings.TrimRight(string(licence), "\n"), "\n") {
		line = strings.TrimRight(line, " \t")
		if line == "" {
			fmt.Fprintln(&b, "//")
			continue
		}
		fmt.Fprintf(&b, "// %s\n", line)
	}
	fmt.Fprintf(&b, `
// %sPhraseFeatures is the model, one feature per line: the group it belongs to,
// the characters it is about, and the weight they carry, tab separated.
//
// %d features over %d groups, the longest %d characters.
const %sPhraseFeatures = `+"`"+`
`, name, len(lines), len(groups), longest, name)
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}
	fmt.Fprintf(&b, "`"+`

// %sPhraseBias is what a boundary's score starts from, doubled.
//
// BudouX begins each score at minus half the sum of every weight in the model,
// so that a boundary no feature has anything to say about scores below zero and
// is not a boundary. Half of an odd sum is not an integer, so what is kept here
// is the sum itself and the features are counted twice against it — which is
// the same comparison with nothing rounded away.
const %sPhraseBias = %d
`, name, name, -total)
	fmt.Print(b.String())
}
