# Positions strings with HarfBuzz in faces with AAT's kerx and trak, and
# writes what it produces, so that shape/kerx_test.go can hold shape/kerx.go
# and shape/trak.go to it.
#
#   make hbaatpos
#
# The faces are those aatpos_fixture.py builds (see there for what each
# states), and TRAK.ttf, the face of HarfBuzz's own aat-trak tests, kept in
# aat-inhouse/ with its cases, which this also checks HarfBuzz still sets as
# they say before writing anything.
#
# Each case is a face, a string, the size it is set at in points (0 for none,
# which is HarfBuzz's and CoreText's 12), whether kerning is on, and the
# glyphs HarfBuzz sets: index, cluster (a byte offset into the UTF-8 string),
# x advance, x offset and y offset, in font units.
import hashlib
import os
import sys

from oracle import harfbuzz

hb = harfbuzz()

HERE = os.path.dirname(os.path.abspath(__file__))
out_path = sys.argv[1]

ACUTE = "́"
STRINGS = {
    "KerxPairs.ttf": ["AV", "VA", "To", "A" + ACUTE + "V", "AVTo", "BC", "CB", "BB", "CC", "DA",
                      "VT", "oT", "BBB", "BBBC", "AVBBo", "ToVA"],
    "KerxMachines.ttf": ["AV", "VA", "AAV", "ATV", "AVAV", "o", "oo", "oBo", "Bo", "A" + ACUTE,
                         "D" + ACUTE, "C" + ACUTE, "A" + ACUTE + "V", "oA" + ACUTE, "CD" + ACUTE],
    "KerxPlanGSUBGPOS.ttf": ["AV", "A" + ACUTE + "V"],
    "KerxPlanGPOS.ttf": ["AV", "A" + ACUTE + "V"],
    "KerxPlanNoKern.ttf": ["AV", "A" + ACUTE, "A" + ACUTE + "V"],
    "KerxPlanLegacyKern.ttf": ["AV", "A" + ACUTE + "V"],
    "TrakCases.ttf": ["AA", "A" + ACUTE + "A", "\U0001F600‍❤", "\U0001F1EF\U0001F1F5",
                      "A\U0001F1EF\U0001F1F5\U0001F1EF"],
    "TrakNoSTAT.ttf": ["AA"],
}
SIZES = {"TrakCases.ttf": [0, 6, 9, 10.5, 12, 24, 100], "TrakNoSTAT.ttf": [0, 6]}


def cases():
    for name, strings in STRINGS.items():
        for s in strings:
            for size in SIZES.get(name, [0]):
                for kern in (True, False):
                    yield name, os.path.join(HERE, "fonts", name), s, size, kern, None
    # HarfBuzz's own tracking cases: the face, a size, and what it expects.
    for line in open(os.path.join(HERE, "aat-inhouse", "tests", "aat-trak.tests"), encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        font, options, codepoints, expected = line.split(";")
        size = 0.0
        if options:
            size = float(options.split("=")[1])
        text = "".join(chr(int(c[2:], 16)) for c in codepoints.split(","))
        path = os.path.join(HERE, "aat-inhouse", "fonts", os.path.basename(font))
        yield os.path.basename(font), path, text, size, True, expected


def names(font, buf):
    """hb-shape's default notation: name=cluster+advance, with offsets."""
    out = []
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        g = font.glyph_to_string(info.codepoint) + f"={info.cluster}"
        if pos.x_offset or pos.y_offset:
            g += f"@{pos.x_offset},{pos.y_offset}"
        g += f"+{pos.x_advance}"
        out.append(g)
    return "[" + "|".join(out) + "]"


out = []
for name, path, text, size, kern, expected in cases():
    data = open(path, "rb").read()
    face = hb.Face(data)
    font = hb.Font(face)
    font.scale = (face.upem, face.upem)
    if size:
        font.ptem = size
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf, {} if kern else {"kern": False})
    if expected is not None and names(font, buf) != expected:
        sys.exit(f"HarfBuzz sets {text!r} in {name} at {size} as {names(font, buf)}, "
                 f"and its own test expects {expected}")
    # uharfbuzz numbers clusters by code point; a byte offset into the UTF-8
    # string is what a Glyph's Cluster is.
    at = [len(text[:k].encode("utf-8")) for k in range(len(text) + 1)]
    glyphs = " ".join(f"{i.codepoint},{at[i.cluster]},{p.x_advance},{p.x_offset},{p.y_offset}"
                      for i, p in zip(buf.glyph_infos, buf.glyph_positions))
    codes = ",".join(f"{ord(c):04X}" for c in text)
    out.append(f"{name} {hashlib.sha256(data).hexdigest()} {codes} {size:g} {int(kern)} {glyphs}")

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/aatpos.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# Each case: the face, its SHA-256, the code points, the size in points\n")
    w.write("# (0 for none), whether kerning is on, and the glyphs HarfBuzz sets —\n")
    w.write("# index, cluster (a byte offset into the UTF-8 string), x advance,\n")
    w.write("# x offset and y offset, in font units.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write(f"# cases {len(out)}\n")
    for line in out:
        w.write(line + "\n")
