# Asks HarfBuzz for the ink of CFF glyphs — hb_font_get_glyph_extents — and
# for what depends on it, and writes the answers, so that shape/cffink_test.go
# can hold shape/cffink.go to them.
#
#   make hbcffink
#
# The companion of shape.py and vertical.py, and the same bargain: the output
# is checked in, so running the test needs a Go toolchain and regenerating it
# needs Python and the pinned uharfbuzz.
#
# The faces are named on the command line as NAME=PATH:
#
#   CFFInk.otf         built by cffink_fixture.py, one glyph for each thing a
#                      charstring can say; every glyph is asked about, and a
#                      few strings are shaped across the page and down it,
#                      because the face positions none of its marks and has
#                      no vertical metrics, so HarfBuzz places the marks and
#                      hangs the glyphs by their ink
#   the rest           the CFF faces in the corpora — Unifont, which states no
#                      VORG, and the CID-keyed Noto CJK faces — each sampled
#                      across its whole range; the whole of every one of them
#                      is compared out of tree, and agrees
#
# A face whose file is not there stops the run rather than being left out: an
# expectation file that quietly covers fewer faces is one the Go test would
# pass on for less.
import hashlib
import sys

from oracle import harfbuzz

hb = harfbuzz()

out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]

# How many glyphs of each corpus face are sampled.
SAMPLE = 400

# The fixture's strings: marks above, below, stacked and attached on a base
# drawn by seac and on ones drawn plainly, a mark with no ink, and a mark whose
# ink HarfBuzz cannot have.
STRINGS = [
    "A\u0301",
    "A\u0323",
    "A\u0323\u0301",
    "A\u0301\u0301",
    "B\u0300\u0301",
    "H\u0327",
    "H\u0328",
    "A\u0328\u0301",
    "AB",
    "HAB\u0301H",
]


def glyphs(buf):
    return " ".join(
        f"{i.codepoint},{p.x_advance},{p.y_advance},{p.x_offset},{p.y_offset}@{i.cluster}"
        for i, p in zip(buf.glyph_infos, buf.glyph_positions))


def shape(font, s, direction):
    buf = hb.Buffer()
    # As UTF-8, so that a cluster is a byte offset, as a Glyph's is.
    buf.add_utf8(s.encode("utf-8"))
    buf.guess_segment_properties()
    if direction:
        buf.direction = direction
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf)
    return buf


out = []
for name, path in faces:
    try:
        data = open(path, "rb").read()
    except FileNotFoundError:
        sys.exit(f"{name}: {path} is not there. Fetch the corpora it is in "
                 "(make notocjk noto-fonts) and run again.")
    face = hb.Face(data)
    font = hb.Font(face)
    out.append(f"face {name} {hashlib.sha256(data).hexdigest()}")
    n = face.glyph_count
    fixture = name == "CFFInk.otf"
    if fixture:
        sample = range(n)
    else:
        sample = sorted(set(range(0, n, max(1, n // SAMPLE))) | {n - 1})
    for gid in sample:
        e = font.get_glyph_extents(gid)
        if e is None:
            out.append(f"E {gid} none")
        else:
            out.append(f"E {gid} {e.x_bearing} {e.y_bearing} {e.width} {e.height}")
    if fixture:
        for s in STRINGS:
            out.append("H " + glyphs(shape(font, s, None)))
            out.append("V " + glyphs(shape(font, s, "ttb")))
        for gid in range(n):
            x, y = font.get_glyph_v_origin(gid)
            out.append(f"M {gid} {-font.get_glyph_v_advance(gid)} {x} {y}")

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/cffink.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, E is one glyph's extents as HarfBuzz states them — x\n")
    w.write("# bearing, y bearing, width and height, in font units — or none where it\n")
    w.write("# has none. For the fixture, H and V are a string of cffink.py shaped\n")
    w.write("# across the page and down it, each glyph as index, x advance, y advance,\n")
    w.write("# x offset and y offset; M is one glyph's vertical advance and origin.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write(f"# strings {len(STRINGS)}\n")
    for line in out:
        w.write(line + "\n")
