# Asks HarfBuzz for the ink of colour glyphs — hb_font_get_glyph_extents on a
# face with COLR or CBDT — and for what depends on it, and writes the answers,
# so that shape/colrink_test.go can hold shape/colrink.go and
# shape/bitmapink.go to them.
#
#   make hbcolrink
#
# The companion of cffink.py, and the same bargain. The faces are built by
# colrink_fixture.py and named on the command line as NAME=PATH:
#
#   ColourInk.ttf      every paint COLR states and every thing painting can do
#                      to a box; every glyph is asked about, and a few strings
#                      are shaped across the page and down it, because the
#                      face positions none of its marks and has no vertical
#                      metrics, so HarfBuzz places the marks and hangs the
#                      glyphs by their painted boxes
#                      — and every glyph again at three weights, since the
#                      face varies and its variable paints move with it
#   ColourInkStatic.ttf  the same face not varying, whose composite glyph has
#                      a component placed by matching points, which a face
#                      from LoadInstance cannot have
#   BitmapInk.ttf      a CBDT with two strikes, every glyph asked about
#
# Every glyph of every colour face in the Google Fonts tree was compared out of
# tree when the reader was written, and every one agrees; these faces are the
# paints and the cases those faces do not reach.
import hashlib
import sys

from oracle import harfbuzz

hb = harfbuzz()

out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]

# The strings shaped in ColourInk: marks above and below colour letters, a
# mark on a letter painted in layers, two marks stacked.
STRINGS = [
    "A\u0301",
    "A\u0323",
    "B\u0301\u0323",
    "A\u0301\u0301",
    "AB",
    "BA\u0323B",
]


def glyphs(buf):
    return " ".join(
        f"{i.codepoint},{p.x_advance},{p.y_advance},{p.x_offset},{p.y_offset}"
        for i, p in zip(buf.glyph_infos, buf.glyph_positions))


def shape(font, s, direction):
    buf = hb.Buffer()
    buf.add_str(s)
    buf.guess_segment_properties()
    if direction:
        buf.direction = direction
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf)
    return buf


# The weights ColourInk is measured at besides its default: both ends of the
# axis, where the deltas are what the fixture states, and a weight between,
# where they are interpolated and rounded.
WEIGHTS = [100, 650, 900]


def extents(font, n):
    for gid in range(n):
        e = font.get_glyph_extents(gid)
        if e is None:
            out.append(f"E {gid} none")
        else:
            out.append(f"E {gid} {e.x_bearing} {e.y_bearing} {e.width} {e.height}")


out = []
for name, path in faces:
    data = open(path, "rb").read()
    digest = hashlib.sha256(data).hexdigest()
    face = hb.Face(data)
    font = hb.Font(face)
    out.append(f"face {name} {digest}")
    extents(font, face.glyph_count)
    if name == "ColourInk.ttf":
        for s in STRINGS:
            out.append("H " + glyphs(shape(font, s, None)))
            out.append("V " + glyphs(shape(font, s, "ttb")))
        for gid in range(face.glyph_count):
            x, y = font.get_glyph_v_origin(gid)
            out.append(f"M {gid} {-font.get_glyph_v_advance(gid)} {x} {y}")
        for w in WEIGHTS:
            font = hb.Font(face)
            font.set_variations({"wght": w})
            out.append(f"face {name}@wght={w} {digest}")
            extents(font, face.glyph_count)

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/colrink.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, and for ColourInk at each weight named after an @, E is\n")
    w.write("# one glyph's extents as HarfBuzz states them — x bearing, y bearing,\n")
    w.write("# width and height, in font units — or none where it has none. For\n")
    w.write("# ColourInk at its default, H and V are a string of colrink.py shaped\n")
    w.write("# across the page and down it, each glyph as index, x advance, y advance,\n")
    w.write("# x offset and y offset; M is one glyph's vertical advance and origin.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write(f"# strings {len(STRINGS)}\n")
    for line in out:
        w.write(line + "\n")
