# Writes the Indic categories HarfBuzz's own generator derives from this
# repository's inputs, for shape/indiccategories_test.go to hold the Indic
# model's categories to.
#
#   python3 testdata/harfbuzz/indiccategories.py <harfbuzz>/src/gen-indic-table.py \
#       testdata/ucd testdata/harfbuzz/indiccategories.expected.txt
#
# HarfBuzz's gen-indic-table.py is the reference implementation of the Indic
# categories, with the corrections it carries beyond Unicode's
# IndicSyllabicCategory.txt, and the one thing Unicode's file does not say at
# all: which characters the model gives a category to. Only the characters of
# the blocks it names get one — the Indic scripts', Vedic Extensions',
# Devanagari Extended's, General Punctuation's and a few more — and every other
# character is Other to the model, whatever Unicode says of it. shape/indic.go
# reads Unicode's file and is a second implementation of the derivation; the
# two have to agree.
#
# The generator is run up to the point it has every character's category and
# stopped there, before it packs them into its own table. It needs Blocks.txt,
# which nothing else here reads, from the same Unicode release in the same
# directory, and the packTab module it imports (pip install packtab), as
# usecategories.py does.
import os
import sys

gen, ucd, out_path = sys.argv[1:4]
src = open(gen, encoding="utf-8").read()
cut = src.index("values = [{_: 1} for _ in defaults]")
src = src[:cut]
files = [os.path.join(ucd, f) for f in (
    "IndicSyllabicCategory.txt", "IndicPositionalCategory.txt", "Blocks.txt")]
sys.argv = [gen] + files
scope = {"__name__": "gen_indic_table"}
exec(compile(src, gen, "exec"), scope)
cats = {u: v[0] for u, v in scope["indic_data"].items() if v[0] != "X"}

version = open(files[0], encoding="utf-8").readline().strip().lstrip("# ")
spans = []
for u in sorted(cats):
    if spans and spans[-1][1] == u - 1 and spans[-1][2] == cats[u]:
        spans[-1][1] = u
    else:
        spans.append([u, u, cats[u]])
with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/indiccategories.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# The Indic category HarfBuzz's gen-indic-table.py derives for each character\n")
    w.write("# it gives one other than X, from this repository's UCD: a range, a space,\n")
    w.write("# the category.\n")
    w.write("# ucd %s\n" % version)
    w.write("# generator %s\n" % os.path.basename(os.path.dirname(os.path.dirname(os.path.abspath(gen)))))
    for lo, hi, cat in spans:
        w.write("%04X..%04X %s\n" % (lo, hi, cat))
print(len(spans), "ranges ->", out_path, file=sys.stderr)
