# Asks HarfBuzz what a variable face states at a point of its design space
# besides its outlines — its font-wide metrics, which MVAR moves, and its
# kerning and mark anchors, which GPOS's VariationIndex devices move — and
# writes the answers, so that shape/instancevaried_test.go can hold a face from
# LoadInstance to them.
#
#   make hbinstancevaried
#
# The companion of verticalinstance.py, which asks about the vertical metrics,
# and of varinstance/instance.py, which asks about the outlines and advances.
#
# Faces are named on the command line as NAME=PATH:
#
#   VariedLayout.ttf       built by variedlayout_fixture.py: every MVAR tag,
#                          and a VariationIndex on every kind of GPOS record
#   VariedLayoutTypo.ttf   the same with USE_TYPO_METRICS set, so that HarfBuzz
#                          reads the ascender, descender and line gap from OS/2
#                          rather than hhea
#   NotoSans-Variable.ttf  the bundled face: MVAR moves its x-height and its
#                          strikeout, and 20,823 devices its kerning and marks
#   NotoSansArabic.ttf     a variable Arabic face: cursive joins and marks
#
# For each face and each of its locations, a 'metric' line is one of the
# font-wide numbers HarfBuzz reports there, by its hb_ot_metrics_tag_t name;
# and an H line a string of instancevaried_test.go's shaped across, each glyph
# as index, x advance, y advance, x offset and y offset in font units.
import hashlib
import sys

from oracle import harfbuzz

hb = harfbuzz()

out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]

LOCATIONS = {
    "VariedLayout.ttf": [{"wght": 100}, {"wght": 250}, {"wght": 400}, {"wght": 650}, {"wght": 900}],
    "VariedLayoutTypo.ttf": [{"wght": 250}, {"wght": 900}],
    "NotoSans-Variable.ttf": [{"wght": 100}, {"wght": 400}, {"wght": 700}, {"wght": 900},
                              {"wght": 700, "wdth": 62.5}],
    "NotoSansArabic.ttf": [{"wght": 100}, {"wght": 900}],
}
FIXTURE = ["AB", "BA", "CE", "DF", "G", "H", "Á́", "ﬁ́", "DE", "DEDE"]
STRINGS = {
    "VariedLayout.ttf": FIXTURE,
    "VariedLayoutTypo.ttf": FIXTURE,
    "NotoSans-Variable.ttf": ["AVATAR Toyota WAVE", "Ta Te To Vo Yo", "é ñ ǘ ẫ q̣̂",
                              "क्षत्रिय नमस्ते",
                              "Αύριο Журнал"],
    "NotoSansArabic.ttf": ["مَرْحَبًا بِالْعَالَمِ",
                           "لا كتاب بيت"],
}


def glyphs(buf):
    return " ".join(
        f"{i.codepoint},{p.x_advance},{p.y_advance},{p.x_offset},{p.y_offset}@{i.cluster}"
        for i, p in zip(buf.glyph_infos, buf.glyph_positions))


def shape(font, s):
    buf = hb.Buffer()
    # As UTF-8, so that a cluster is a byte offset, as a Glyph's is.
    buf.add_utf8(s.encode("utf-8"))
    buf.guess_segment_properties()
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf, {})
    return buf


out = []
for name, path in faces:
    data = open(path, "rb").read()
    face = hb.Face(data)
    out.append(f"face {name} {hashlib.sha256(data).hexdigest()}")
    for loc in LOCATIONS[name]:
        font = hb.Font(face)
        font.set_variations(loc)
        out.append("location " + " ".join(f"{k}={v:g}" for k, v in loc.items()))
        for tag in hb.OTMetricsTag:
            v = font.get_metric_position(tag)
            if v is not None:
                out.append(f"metric {tag.name} {v}")
        for s in STRINGS[name]:
            out.append("H " + glyphs(shape(font, s)))

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/instancevaried.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, at each location: a metric line is a font-wide number\n")
    w.write("# HarfBuzz reports there, by its hb_ot_metrics_tag_t name, in font units;\n")
    w.write("# an H line a string of instancevaried_test.go shaped across, each glyph as\n")
    w.write("# index, x advance, y advance, x offset and y offset in font units.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    for line in out:
        w.write(line + "\n")
