# Asks HarfBuzz what each face's 'rtlm' feature makes of the glyph of every
# character it maps, and writes the answers, so that shape/mirroredform_test.go
# can hold Face.MirroredForm to them.
#
#   make hbmirroredform
#
# The question is MathML Core's "an OpenType rtlm variant of g" (§5.3.2), and
# HarfBuzz is asked it the one way it can be: the character shaped alone, left
# to right — where HarfBuzz mirrors nothing and applies no 'rtlm' of its own —
# once as it is and once with 'rtlm' turned on for the whole run. Where the
# first gives the character's own glyph, the second is what 'rtlm' made of
# it: a different glyph is the form, the same glyph is none, and more than
# one glyph is not a mirrored form of it either. Where the first does not give
# the character's own glyph — another feature changed it before 'rtlm' could
# be asked — the character is left out and counted, and the Go test asks
# nothing of it.
#
# The faces are named on the command line as NAME=PATH:
#
#   MirroredForms.ttf   built by mirroredform_fixture.py
#   the rest            the math fonts in the corpora: radical-rtlm.woff from
#                       the suite's fonts/math (unwrapped by fontTools before
#                       HarfBuzz reads it), and Noto Sans Math and STIX Two Math
#                       from the Google Fonts library
#
# A face whose file is not there stops the run rather than being left out.
import hashlib
import io
import sys

from oracle import fonttools, harfbuzz

hb = harfbuzz()
fonttools()
from fontTools.ttLib import TTFont  # noqa: E402

out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]


def sfnt(data):
    """The font as an sfnt HarfBuzz reads: a WOFF unwrapped, its tables as
    they were."""
    if data[:4] != b"wOFF":
        return data
    f = TTFont(io.BytesIO(data), lazy=True)
    f.flavor = None
    buf = io.BytesIO()
    f.save(buf, reorderTables=False)
    return buf.getvalue()


def shape(font, ch, features):
    buf = hb.Buffer()
    buf.add_str(ch)
    buf.guess_segment_properties()
    buf.direction = "ltr"
    hb.shape(font, buf, features)
    return [i.codepoint for i in buf.glyph_infos]


out = [
    "# Generated by testdata/harfbuzz/mirroredform.py. DO NOT EDIT.",
    "#",
    "# For each face: M a character and the glyph its glyph's 'rtlm' form is,",
    "# for every character whose form differs from its glyph; S the number of",
    "# characters left out because shaping changed their glyph before 'rtlm'",
    "# was asked; N the number of characters asked. A character asked and not",
    "# listed has no form. Characters and glyphs are decimal.",
    "# harfbuzz " + hb.version_string(),
    "# uharfbuzz " + hb.__version__,
]
for name, path in faces:
    try:
        data = open(path, "rb").read()
    except FileNotFoundError:
        sys.exit(f"{name}: {path} is not there. Fetch the corpora it is in "
                 "(make wpt googlefonts) and run again.")
    font = hb.Font(hb.Face(sfnt(data)))
    cmap = TTFont(io.BytesIO(data)).getBestCmap()
    gids = {n: i for i, n in enumerate(TTFont(io.BytesIO(data)).getGlyphOrder())}
    out.append("face %s %s" % (name, hashlib.sha256(data).hexdigest()))
    skipped = asked = 0
    for cp in sorted(cmap):
        if cp >= 0xD800 and cp <= 0xDFFF:
            continue
        g = gids[cmap[cp]]
        base = shape(font, chr(cp), {})
        if base != [g]:
            skipped += 1
            continue
        asked += 1
        got = shape(font, chr(cp), {"rtlm": True})
        if len(got) == 1 and got[0] != g:
            out.append("M %d %d" % (cp, got[0]))
    out.append("S %d" % skipped)
    out.append("N %d" % asked)

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("wrote", out_path)
