# Asks HarfBuzz which OpenType script tags a run is looked up under, for each of
# a list of BCP 47 language tags, and writes the answers.
#
# The output is checked in and is what shape/language_test.go compares
# shape.otLanguage.scriptTags against. It is the other half of langtags.py:
# hb_ot_tags_from_script_and_language answers with language system tags *and*
# script tags, and what a language tag can say about the script is HarfBuzz's
# private-use subtag "-hbsc", which names a script tag in place of the run's
# own. Each tag is asked about for a Latin run and a Devanagari one, since the
# second has three tags of its own and the first one.
#
#   python3 testdata/harfbuzz/scripttags.py testdata/harfbuzz/scripttags.expected.txt
#
# uharfbuzz does not wrap the function, so it is called through ctypes in the
# library uharfbuzz carries, as langtags.py calls it.
import ctypes
import glob
import os
import random
import sys

from oracle import harfbuzz

hb = harfbuzz()

out_path = sys.argv[1]

lib = ctypes.CDLL(glob.glob(os.path.join(os.path.dirname(hb.__file__), "_harfbuzz*.so"))[0])
lib.hb_language_from_string.restype = ctypes.c_void_p
lib.hb_language_from_string.argtypes = [ctypes.c_char_p, ctypes.c_int]
lib.hb_ot_tags_from_script_and_language.argtypes = [
    ctypes.c_uint32, ctypes.c_void_p,
    ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.c_uint32),
    ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.c_uint32),
]

# HB_OT_MAX_TAGS_PER_SCRIPT: what the shaper asks for.
MAX_TAGS = 3


def tag(s):
    return int.from_bytes(s.encode("ascii"), "big")


SCRIPTS = [("Latn", tag("Latn")), ("Deva", tag("Deva"))]


def script_tags(script, lang):
    n = ctypes.c_uint(MAX_TAGS)
    arr = (ctypes.c_uint32 * MAX_TAGS)()
    lib.hb_ot_tags_from_script_and_language(
        script, lib.hb_language_from_string(lang.encode("latin-1"), -1),
        ctypes.byref(n), arr, None, None)
    return [arr[i] for i in range(n.value)]


def spell(t):
    b = t.to_bytes(4, "big")
    if all(0x20 <= c <= 0x7E for c in b) and b"|" not in b:
        return b.decode("ascii")
    return "0x%08x" % t


# The private-use part, spelled every way HarfBuzz's parse_private_use_subtag
# reads or refuses: a tag spelled out, short, long, in capitals, in hex, in
# hex too short or not hex at all, 'DFLT' both ways, with "-hbot" before and
# after it, and "-hbsc" not at the start of a subtag.
PRIVATE = [
    "x-hbscdev2", "x-hbscDEV2", "x-hbsclatn", "x-hbscdflt", "x-hbscDFLT",
    "x-hbscab", "x-hbsca", "x-hbsc", "x-hbsc-", "x-hbscarabic", "x-hbscdev21",
    "x-hbsc1234", "x-hbsc-64657632", "x-hbsc-6465763", "x-hbsc-646576320",
    "x-hbsc-zzzzzzzz", "x-hbsc-44464c54", "x-hbsc-00000000", "x-hbsc-7c7c7c7c",
    "x-foo-hbsclatn", "x-hbotmar-hbscdev2", "x-hbscdev2-hbotmar", "x-hbsc_dev2",
    "x-ahbscdev2", "x-foohbscdev2", "x-hbscmym2", "x-hbscknd3", "x-hbsc-hbscabc",
    "x-hbot-hbscabc", "x-y", "x-hbot", "x",
]
PREFIXES = ["", "und-", "en-", "sr-latn-", "zh-hant-hk-", "en-u-ca-gregory-",
            "hi-a-bbb-", "mr-", "a-", "EN_"]
langs = set()
for pre in PREFIXES:
    for priv in PRIVATE:
        langs.add(pre + priv)
langs.update(["", "en", "hi", "und-hbscdev2", "en-hbsclatn", "hbsc", "x-hbsc x",
              "en-x-hbscdev2 x"])

rng = random.Random(20260924)
pieces = ["x", "hbscdev2", "hbsclatn", "hbscab", "hbsc", "hbot", "hbotmar", "en",
          "hi", "u", "a", "latn", "64657632", "hbscDFLT", "und", "zh", "hant"]
for _ in range(2000):
    k = rng.randint(1, 6)
    langs.add("-".join(rng.choice(pieces) for _ in range(k)))

langs = sorted(langs)
with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/scripttags.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# The OpenType script tags HarfBuzz's hb_ot_tags_from_script_and_language\n")
    w.write(f"# gives a run of each script below in each BCP 47 tag, at most {MAX_TAGS}, in\n")
    w.write("# order: the tag, then a tab and the tags separated by '|' for each script.\n")
    w.write("# A tag that is not printable is written as 0x and eight hex digits.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write("# scripts " + " ".join(name for name, _ in SCRIPTS) + "\n")
    w.write(f"# cases {len(langs)}\n")
    for l in langs:
        w.write(l + "".join("\t" + "|".join(spell(t) for t in script_tags(s, l))
                            for _, s in SCRIPTS) + "\n")
print(f"{len(langs)} cases -> {out_path}", file=sys.stderr)
