# Shapes the font-variant corpus with HarfBuzz and writes what it produced.
#
# The companion of shape.py, and the same bargain: the output is checked in, so
# running the test needs a Go toolchain and regenerating it needs Python and
# uharfbuzz.
#
#   make hbshaping
#
# What it adds is the *features*. shape.py asks HarfBuzz to shape a string with
# whatever the font turns on by itself; this asks it to shape one with the
# features a CSS declaration turns on, which is a different question and the one
# the font-variant family answers.
#
# # The table below is the point, and it is deliberately a second copy
#
# Which OpenType features a CSS value asks for is stated twice: here, and in the
# Go package under test. That is not duplication to be tidied away — it is what
# makes this an oracle rather than a mirror. If the Go table said "oldstyle-nums
# is 'lnum'" the two would disagree here and the test would fail, where a Go test
# reading the Go table would agree with itself and prove nothing.
#
# The same goes for the *order* they are applied in. Nothing here says an order:
# HarfBuzz is handed a set and walks the font's lookups in index order, which is
# the behaviour applyRequestedFeatures exists to reproduce.
import hashlib
import sys

import uharfbuzz as hb

TAGS = {
    "caps": {
        "small-caps": ["smcp"],
        "all-small-caps": ["c2sc", "smcp"],
        "petite-caps": ["pcap"],
        "all-petite-caps": ["c2pc", "pcap"],
        "unicase": ["unic"],
        "titling-caps": ["titl"],
    },
    "numeric": {
        "lining-nums": ["lnum"],
        "oldstyle-nums": ["onum"],
        "proportional-nums": ["pnum"],
        "tabular-nums": ["tnum"],
        "diagonal-fractions": ["frac"],
        "stacked-fractions": ["afrc"],
        "ordinal": ["ordn"],
        "slashed-zero": ["zero"],
    },
    "east-asian": {
        "jis78": ["jp78"], "jis83": ["jp83"], "jis90": ["jp90"], "jis04": ["jp04"],
        "simplified": ["smpl"], "traditional": ["trad"],
        "full-width": ["fwid"], "proportional-width": ["pwid"],
        "ruby": ["ruby"],
    },
    "position": {"sub": ["subs"], "super": ["sups"]},
}


def tags_of(spec):
    """The OpenType tags a spec asks for. "-" is none."""
    if spec == "-":
        return []
    out = []
    for group in spec.split(", "):
        prop, _, values = group.partition("=")
        table = TAGS[prop]
        for value in values.split(" "):
            out.extend(table[value])
    return out


def split_spec(spec):
    """Splits "caps=small-caps numeric=oldstyle-nums" into its groups.

    The separator is a space before a "<prop>=", which is what lets a value
    itself hold spaces — "numeric=ordinal slashed-zero" is one group of two.
    """
    if spec == "-":
        return "-"
    parts, cur = [], []
    for word in spec.split(" "):
        if "=" in word and cur:
            parts.append(" ".join(cur))
            cur = []
        cur.append(word)
    parts.append(" ".join(cur))
    return ", ".join(parts)


font_path, corpus_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

data = open(font_path, "rb").read()
face = hb.Face(hb.Blob(data))

cases = []
for line in open(corpus_path, encoding="utf-8"):
    line = line.rstrip("\n")
    if line == "" or line.startswith("#"):
        continue
    spec, _, text = line.partition("\t")
    cases.append((spec, text))

out = []
for spec, text in cases:
    tags = tags_of(split_spec(spec))
    font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf, {t: True for t in tags})
    fields = []
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        if pos.x_offset or pos.y_offset:
            fields.append(f"{info.codepoint},{pos.x_advance},{pos.x_offset},{pos.y_offset}")
        else:
            fields.append(f"{info.codepoint},{pos.x_advance}")
    out.append(" ".join(fields))

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/shapefeatures.py. DO NOT EDIT.\n")
    w.write(f"# font-sha256 {hashlib.sha256(data).hexdigest()}\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    w.write(f"# cases {len(out)}\n")
    for line in out:
        w.write(line + "\n")

print(f"{len(out)} cases -> {out_path}", file=sys.stderr)
