# Writes the Universal Shaping Engine categories HarfBuzz's own generator
# derives from this repository's inputs, for shape/usecategories_test.go to
# hold cmd/genuse's table to.
#
#   python3 testdata/harfbuzz/usecategories.py <harfbuzz>/src/gen-use-table.py \
#       testdata/ucd testdata/ms-use testdata/harfbuzz/usecategories.expected.txt
#
# HarfBuzz's gen-use-table.py is the reference implementation of the
# derivation, with the corrections it carries beyond the engine's own files;
# cmd/genuse is a second implementation of it. Run over the same Unicode
# release and the same correction files, the two have to agree, and where they
# do not, one of them has a correction the other lacks — which is how the
# Grantha and Tirhuta positions and the Lepcha final modifier were found.
#
# The generator is run up to the point it has every character's category and
# stopped there, before it packs them into its own table. It needs
# Blocks.txt, which nothing else here reads, from the same Unicode release in
# the same directory, and the packTab module it imports (pip install packtab).
import os
import sys

gen, ucd, msuse, out_path = sys.argv[1:5]
src = open(gen, encoding="utf-8").read()
cut = src.index("use_data = map_to_use(combined)")
src = src[:cut] + "use_data = map_to_use(combined)\n"
files = [os.path.join(ucd, f) for f in (
    "IndicSyllabicCategory.txt", "IndicPositionalCategory.txt", "ArabicShaping.txt",
    "DerivedCoreProperties.txt", "UnicodeData.txt", "Blocks.txt", "Scripts.txt")]
files += [os.path.join(msuse, f) for f in (
    "IndicSyllabicCategory-Additional.txt", "IndicPositionalCategory-Additional.txt")]
sys.argv = [gen] + files
scope = {"__name__": "gen_use_table"}
exec(compile(src, gen, "exec"), scope)
use = {u: v[0] for u, v in scope["use_data"].items() if v[0] != "O"}

version = open(files[0], encoding="utf-8").readline().strip().lstrip("# ")
spans = []
for u in sorted(use):
    if spans and spans[-1][1] == u - 1 and spans[-1][2] == use[u]:
        spans[-1][1] = u
    else:
        spans.append([u, u, use[u]])
with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/usecategories.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# The USE category HarfBuzz's gen-use-table.py derives for each character\n")
    w.write("# it gives one other than O, from this repository's UCD and ms-use files:\n")
    w.write("# a range, a space, the category with its position.\n")
    w.write("# ucd %s\n" % version)
    w.write("# generator %s\n" % os.path.basename(os.path.dirname(os.path.dirname(os.path.abspath(gen)))))
    for lo, hi, cat in spans:
        w.write("%04X..%04X %s\n" % (lo, hi, cat))
print(len(spans), "ranges ->", out_path, file=sys.stderr)
