# Writes the scripts HarfBuzz sets with the Universal Shaping Engine, as its
# own source states them, for shape/usescripts_test.go to hold the package's
# list to.
#
#   python3 testdata/harfbuzz/usescripts.py <harfbuzz>/src \
#       testdata/harfbuzz/usescripts.expected.txt
#
# The list is hb_ot_shaper_categorize's: the cases of its switch whose arm
# ends in the universal engine, in src/hb-ot-shaper.hh, each an HB_SCRIPT_
# name that src/hb-script-list.h gives an ISO 15924 code. It is a decision of
# HarfBuzz's rather than a property Unicode publishes — a script is added when
# HarfBuzz decides its text wants the engine, and New Tai Lue was taken out
# when it decided it did not — so it is read from the release the oracle is
# pinned to, run from a source checkout as usecategories.py is.
#
# The arm for the Indic scripts ends in the engine too, for a font written
# under their third-generation tags; that is a choice by tag, which the
# package makes in categorize, and those scripts are not in this list.
import os
import re
import sys

src, out_path = sys.argv[1:3]
shaper = open(os.path.join(src, "hb-ot-shaper.hh"), encoding="utf-8").read()
names = open(os.path.join(src, "hb-script-list.h"), encoding="utf-8").read()
codes = {m.group(1): "".join(m.group(2, 3, 4, 5)) for m in re.finditer(
    r"HB_SCRIPT_(\w+)\s*=\s*HB_TAG\s*\('(.)',\s*'(.)',\s*'(.)',\s*'(.)'\)", names)}

body = shaper[shaper.index("hb_ot_shaper_categorize"):]
body = body[:body.index("\n}\n")]

# Each arm: its cases, then the shapers its statements return.
arms, cases, returns = [], [], []
for line in body.split("\n"):
    m = re.match(r"\s*case HB_SCRIPT_(\w+):", line)
    if m:
        if returns:
            arms.append((cases, returns))
            cases, returns = [], []
        cases.append(m.group(1))
        continue
    r = re.search(r"return &_hb_ot_shaper_(\w+);", line)
    if r:
        returns.append(r.group(1))
arms.append((cases, returns))

use = sorted(codes[c] for cases, returns in arms
             if "use" in returns and set(returns) <= {"use", "default"} for c in cases)
version = re.search(r"#define HB_VERSION_STRING \"([^\"]+)\"",
                    open(os.path.join(src, "hb-version.h"), encoding="utf-8").read()).group(1)
with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/usescripts.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# The scripts hb_ot_shaper_categorize sets with the universal engine,\n")
    w.write("# by ISO 15924 code, one to a line.\n")
    w.write("# generator harfbuzz-%s\n" % version)
    for code in use:
        w.write(code + "\n")
print(len(use), "scripts ->", out_path, file=sys.stderr)
