# Asks HarfBuzz for the ink and the outlines of variable-composite glyphs —
# hb_font_get_glyph_extents and hb_font_draw_glyph on a face with a VARC
# table — and fontTools for the outlines too, and writes the answers, so that
# shape/varc_test.go can hold shape/varc.go to them.
#
#   make hbvarc
#
# The faces are built by varc_fixture.py, named on the command line as
# NAME=PATH. Each is asked at its default, as HarfBuzz reads a face nobody set
# a location on, and VarComposite.ttf at each location in LOCATIONS too, set
# as a caller sets one:
#
#   E    one glyph's extents: x bearing, y bearing, width and height, or none
#   H    one glyph's path as HarfBuzz draws it: M for the start of a contour, L
#        for a line, Z for its end, each point as HarfBuzz hands it to a pen
#   F    one VARC glyph's path as fontTools' glyph set draws it at the
#        location, in the same form, or 'unavailable' and why where fontTools
#        cannot draw it
import hashlib
import sys

from oracle import fonttools, harfbuzz

hb = harfbuzz()
fonttools()
from fontTools.pens.recordingPen import RecordingPen  # noqa: E402
from fontTools.ttLib import TTFont  # noqa: E402


class Flat:
    """A pen that records a path and takes no components, so that fontTools'
    glyph set draws every VARC component out into its outlines."""

    def __init__(self):
        self.value = []

    def moveTo(self, p):
        self.value.append(("moveTo", (p,)))

    def lineTo(self, p):
        self.value.append(("lineTo", (p,)))

    def qCurveTo(self, *pts):
        self.value.append(("qCurveTo", pts))

    def curveTo(self, *pts):
        self.value.append(("curveTo", pts))

    def closePath(self):
        self.value.append(("closePath", ()))

    def endPath(self):
        self.value.append(("endPath", ()))


out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]

LOCATIONS = [
    {"wght": 400},
    {"wght": 900},
    {"wght": 100},
    {"wght": 650, "0000": 0.5},
    {"wght": 250, "0000": -0.75, "0001": 0.3},
    {"wght": 900, "0001": 0.95},
    {"wght": 650},
    {"wght": 550},
    {"wght": 570},
]


def num(v):
    return repr(float(v))


def path(value):
    out = []
    for op, args in value:
        if op == "moveTo":
            out.append("M %s %s" % (num(args[0][0]), num(args[0][1])))
        elif op == "lineTo":
            out.append("L %s %s" % (num(args[0][0]), num(args[0][1])))
        elif op == "closePath":
            out.append("Z")
        elif op == "endPath":
            out.append("Z")
        else:
            sys.exit("a path draws a %s, and the fixture is lines only" % op)
    return " ".join(out)


def name(loc):
    return ",".join("%s=%g" % kv for kv in sorted(loc.items()))


out = []
for fname, file in faces:
    data = open(file, "rb").read()
    digest = hashlib.sha256(data).hexdigest()
    face = hb.Face(data)
    ft = TTFont(file)
    order = ft.getGlyphOrder()
    # The faces beside VarComposite.ttf are about whether the table is read
    # at all, which its default says.
    locations = [None] + (LOCATIONS if fname == "VarComposite.ttf" else [])
    try:
        covered = set(ft["VARC"].table.Coverage.glyphs)
    except Exception:  # noqa: BLE001 — a table fontTools cannot read either
        covered = set()
    for loc in locations:
        font = hb.Font(face)
        if loc is not None:
            font.set_variations(loc)
        out.append(f"face {fname}@{'default' if loc is None else name(loc)} {digest}")
        for gid in range(face.glyph_count):
            e = font.get_glyph_extents(gid)
            out.append(f"E {gid} none" if e is None else
                       f"E {gid} {e.x_bearing} {e.y_bearing} {e.width} {e.height}")
        if fname != "VarComposite.ttf":
            continue
        for gid in range(face.glyph_count):
            pen = RecordingPen()
            font.draw_glyph_with_pen(gid, pen)
            out.append(f"H {gid} {path(pen.value)}")
        glyphs = ft.getGlyphSet(location=loc or {})
        for gid, g in enumerate(order):
            if g not in covered:
                continue
            pen = Flat()
            try:
                glyphs[g].draw(pen)
            except Exception as e:  # noqa: BLE001 — what fontTools cannot draw is recorded
                out.append(f"F {gid} unavailable {type(e).__name__}")
                continue
            out.append(f"F {gid} {path(pen.value)}")

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/varc.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face at its default, with no coordinates, and at each location:\n")
    w.write("# E is one glyph's extents as HarfBuzz states them, H its path as HarfBuzz\n")
    w.write("# draws it, and F a VARC glyph's path as fontTools draws it.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    for line in out:
        w.write(line + "\n")
