# Asks HarfBuzz how a variable face set upright advances and hangs its glyphs
# away from its default instance, and how a kern table's vertical subtables
# kern a run set upright, and writes the answers, so that
# shape/verticalinstance_test.go can hold LoadInstance and the legacy kern
# table to them.
#
#   make hbverticalinstance
#
# The companion of vertical.py, which asks the same questions at the default
# instance and of faces without a vertical kern table.
#
# Faces are named on the command line as NAME=PATH:
#
#   VerticalVariable.ttf        built by verticalinstance_fixture.py: the
#   VerticalVariableNoVVAR.ttf  same variable face with VVAR and without, so
#                               that the advance comes from VVAR in one and from
#                               gvar's phantom points in the other
#   NotoSansJP-VF.ttf           a real variable face with vertical metrics and no
#                               VVAR (NOTO_FONTS), sampled across its glyphs
#   VerticalKern.ttf            built by verticalinstance_fixture.py: a kern
#                               table with vertical subtables, and a 'vkrn'
#   VerticalKernNoVkrn.ttf      the same with no 'vkrn'
#
# For each variable face and each of its locations, M lines are a glyph's
# vertical advance and origin, and V lines a string shaped top to bottom, at
# that location. For the kerned faces, V and H lines are a string shaped top
# to bottom and across, with the features the line names: vkrn asked for, or
# nokern, kern turned off.
import hashlib
import sys

from oracle import harfbuzz

hb = harfbuzz()

out_path = sys.argv[1]
faces = [a.split("=", 1) for a in sys.argv[2:]]

LOCATIONS = {
    "VerticalVariable.ttf": [100, 300, 500, 900],
    "VerticalVariableNoVVAR.ttf": [100, 300, 500, 900],
    "NotoSansJP-VF.ttf": [100, 400, 700, 900],
}
STRINGS = {
    "VerticalVariable.ttf": ["ABD", "A B"],
    "VerticalVariableNoVVAR.ttf": ["ABD", "A B"],
    "NotoSansJP-VF.ttf": ["\u65e5\u672c\u8a9e", "\u3042\u3001\u3044\u3002", "\uff08\u6f22\u5b57\uff09"],
    "VerticalKern.ttf": ["ABCA", "CAB", "AB BC", "BCBC", "A\u0301B"],
    "VerticalKernNoVkrn.ttf": ["ABCA", "CAB", "AB BC", "BCBC", "A\u0301B"],
}
# How many glyphs of a corpus face are sampled at each location.
SAMPLE = 400


def glyphs(buf):
    return " ".join(
        f"{i.codepoint},{p.x_advance},{p.y_advance},{p.x_offset},{p.y_offset}"
        for i, p in zip(buf.glyph_infos, buf.glyph_positions))


def shape(font, s, direction, feats):
    buf = hb.Buffer()
    buf.add_str(s)
    buf.guess_segment_properties()
    if direction:
        buf.direction = direction
    buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
    hb.shape(font, buf, feats)
    return buf


out = []
for name, path in faces:
    try:
        data = open(path, "rb").read()
    except FileNotFoundError:
        sys.exit(f"{name}: {path} is not there. Fetch the corpora it is in "
                 "(make noto-fonts) and run again.")
    face = hb.Face(data)
    out.append(f"face {name} {hashlib.sha256(data).hexdigest()}")
    n = face.glyph_count
    if name in LOCATIONS:
        sample = range(n) if n < SAMPLE else range(0, n, n // SAMPLE)
        for wght in LOCATIONS[name]:
            font = hb.Font(face)
            font.set_variations({"wght": wght})
            out.append(f"location wght={wght}")
            for gid in sample:
                x, y = font.get_glyph_v_origin(gid)
                out.append(f"M {gid} {-font.get_glyph_v_advance(gid)} {x} {y}")
            for s in STRINGS[name]:
                out.append("V - " + glyphs(shape(font, s, "ttb", {})))
        continue
    font = hb.Font(face)
    out.append("location -")
    for s in STRINGS[name]:
        for tag in ("-", "vkrn"):
            feats = {} if tag == "-" else {tag: True}
            out.append(f"V {tag} " + glyphs(shape(font, s, "ttb", feats)))
        out.append("H - " + glyphs(shape(font, s, None, {})))
        out.append("H nokern " + glyphs(shape(font, s, None, {"kern": False})))

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/harfbuzz/verticalinstance.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, at each location: M is a glyph's vertical advance and\n")
    w.write("# origin; V and H are a string of verticalinstance.py shaped top to bottom\n")
    w.write("# and across with the feature named (- for none), each glyph as index,\n")
    w.write("# x advance, y advance, x offset and y offset in font units.\n")
    w.write(f"# harfbuzz {hb.version_string()}\n")
    w.write(f"# uharfbuzz {hb.__version__}\n")
    for line in out:
        w.write(line + "\n")
