// Command genfullwidth generates the mapping "text-transform: full-width" asks
// for, from Unicode's own UnicodeData.txt.
//
// CSS Text 3 §2.1.1 says the value "puts all characters in fullwidth form", and
// that a character with no fullwidth form is left alone. It does not enumerate
// them, and it does not have to: Unicode already states which characters are a
// wide or a narrow form of which others, as the compatibility decompositions
// tagged <wide> and <narrow>.
//
// The two tags run in opposite directions and both end at the same place.
//
//	FF21;FULLWIDTH LATIN CAPITAL LETTER A;…;<wide> 0041;…
//	FF71;HALFWIDTH KATAKANA LETTER A;…;<narrow> 30A2;…
//
// The first says U+FF21 is the wide form of "A", so "A" maps *to* it. The second
// says U+FF71 is the narrow form of "ア", so it maps *from* itself to that. So a
// <wide> decomposition is read backwards and a <narrow> one forwards, and
// together they are every character that has a fullwidth form: 226 of them, from
// the space through the halfwidth won sign.
//
// Deriving it rather than typing it is not only about the length of the list.
// The suite's text-transform-fullwidth-010 is exhaustive — every character with
// a mapping, and its expected result beside it — and the rule above reproduces
// that reference exactly, character for character. A typed table would be a
// second statement of the same thing, wrong wherever the typing was.
//
// What is not here is the reverse direction. CSS Text 4 also has a "full-size"
// value that undoes this, and nothing in this engine asks for it yet; adding it
// is reading the same two tags the other way round.
//
//	go run ./cmd/genfullwidth <UnicodeData.txt> > paragraph/widthtable.go
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genfullwidth <UnicodeData.txt>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type pair struct {
		from, to rune
		name     string
	}
	var pairs []pair
	var wide, narrow int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for line := 1; sc.Scan(); line++ {
		// code;name;category;combining;bidi;decomposition;…
		fields := strings.Split(sc.Text(), ";")
		if len(fields) < 6 {
			continue
		}
		code := parseRune(fields[0], line)
		d := strings.Fields(fields[5])
		if len(d) != 2 {
			// Every <wide> and <narrow> decomposition is one character long, and
			// a second one would be a mapping this cannot express. Say so rather
			// than dropping it.
			if len(d) > 0 && (d[0] == "<wide>" || d[0] == "<narrow>") {
				fmt.Fprintf(os.Stderr, "line %d: %s decomposes to %d characters\n",
					line, fields[0], len(d)-1)
				os.Exit(1)
			}
			continue
		}
		switch d[0] {
		case "<wide>":
			// The wide form is the answer, and the character it decomposes to
			// is the question.
			pairs = append(pairs, pair{parseRune(d[1], line), code, fields[1]})
			wide++
		case "<narrow>":
			pairs = append(pairs, pair{code, parseRune(d[1], line), fields[1]})
			narrow++
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].from < pairs[j].from })
	for i := 1; i < len(pairs); i++ {
		if pairs[i-1].from == pairs[i].from {
			fmt.Fprintf(os.Stderr, "%#04X has two fullwidth forms, %#04X and %#04X\n",
				pairs[i].from, pairs[i-1].to, pairs[i].to)
			os.Exit(1)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/genfullwidth from Unicode's UnicodeData.txt.
// DO NOT EDIT.

package paragraph

// The fullwidth form of every character that has one. Unicode 17.0.0.
//
// %d mappings: %d read backwards from a <wide> decomposition and %d forwards
// from a <narrow> one — see cmd/genfullwidth, which is also where the reason
// they are derived rather than typed is. Sorted by the character transformed,
// because that is what is searched for.

// widthPair is one character and its fullwidth form.
type widthPair struct {
	from, to rune
}

var fullWidthForms = [...]widthPair{
`, len(pairs), wide, narrow)
	for _, p := range pairs {
		fmt.Fprintf(&b, "\t{%#04X, %#04X}, // %s\n", p.from, p.to, p.name)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "generated source does not parse:", err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}

func parseRune(field string, line int) rune {
	v, err := strconv.ParseUint(strings.TrimSpace(field), 16, 32)
	if err != nil {
		fmt.Fprintf(os.Stderr, "line %d: %v\n", line, err)
		os.Exit(1)
	}
	return rune(v)
}
