# Transcribes MathML Core's operator dictionary, appendix B, from the
# specification itself, pinned at one snapshot:
#
#   python3 testdata/mathml/opdict.py SPEC.html layout/mathopdict.go testdata/mathml/operator-dictionary.txt
#
# where SPEC.html is https://www.w3.org/TR/2025/CR-mathml-core-20250624/ as
# fetched. Two things come out of one document, from two of its parts that
# are written independently of each other:
#
#   - layout/mathopdict.go, the compact tables of B.1 (figures 24 to 28) the
#     engine looks operators up in, by B.1's algorithm;
#   - operator-dictionary.txt, B.2's human-readable dictionary, one operator
#     and form a line, which layout/mathopdict_test.go holds the lookup to.
#
# A transcription error in either shows as a disagreement between them.
import html.parser
import re
import sys

src, out_go, out_txt = sys.argv[1:4]


class Text(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.out, self.skip = [], 0

    def handle_starttag(self, t, a):
        if t in ("script", "style"):
            self.skip += 1
        if t in ("p", "div", "li", "tr", "br", "dt", "dd", "section", "table", "figcaption"):
            self.out.append("\n")
        if t in ("td", "th"):
            self.out.append(" | ")

    def handle_endtag(self, t):
        if t in ("script", "style"):
            self.skip -= 1
        if t in ("p", "div", "li", "tr", "dt", "dd"):
            self.out.append("\n")

    def handle_data(self, d):
        if not self.skip:
            self.out.append(re.sub(r"\s+", " ", d))


p = Text()
p.feed(open(src, encoding="utf-8").read())
text = "".join(p.out)
if "CR-mathml-core-20250624" not in text and "24 June 2025" not in text:
    sys.exit("this is not the 24 June 2025 snapshot the tables are pinned to")


def codepoints(listing):
    """U+XXXX singles, {U+XXXX} and [U+XXXX–U+YYYY] ranges, as ints."""
    cps = []
    for m in re.finditer(r"\[U\+([0-9A-F]+)–U\+([0-9A-F]+)\]|\{?U\+([0-9A-F]+)\}?", listing):
        if m.group(1):
            cps.extend(range(int(m.group(1), 16), int(m.group(2), 16) + 1))
        else:
            cps.append(int(m.group(3), 16))
    return cps


def entries(listing):
    out = []
    for m in re.finditer(r"\[0x([0-9A-F]+)–0x([0-9A-F]+)\]|\{0x([0-9A-F]+)\}", listing):
        if m.group(1):
            out.extend(range(int(m.group(1), 16), int(m.group(2), 16) + 1))
        else:
            out.append(int(m.group(3), 16))
    return out


ascii2 = re.search(r"Operators_2_ascii_chars \| 18 entries \(2-characters ASCII strings\): (.*?) \n", text).group(1)
ascii2 = re.findall(r"'(..)'", ascii2)
assert len(ascii2) == 18, ascii2

cats = {}
for m in re.finditer(r"\| (\d+) entries[^|]*? in (infix|prefix|postfix) form: (.*?) \| ([A-M])\b", text):
    n, form, listing, cat = int(m.group(1)), m.group(2), m.group(3), m.group(4)
    cps = codepoints(listing)
    assert len(cps) == n, (cat, n, len(cps))
    cats[cat] = (form, cps)
assert sorted(cats) == list("ABCDEFGHIJKLM"), sorted(cats)

fig27 = re.search(r"716 entries \(236 ranges of length at most 16\): (.*?)\s*Figure 27", text, re.S).group(1)
fig27 = entries(fig27)
assert len(fig27) == 716 and fig27 == sorted(fig27, key=lambda e: e % 0x4000), len(fig27)

axis = re.search(r"is block\.\s*(U\+003D, .*?)\s*Figure 28", text, re.S).group(1)
axis = codepoints(axis)
assert len(axis) == 246 and axis == sorted(axis), len(axis)

w = open(out_go, "w", encoding="utf-8")
w.write("// Code generated by testdata/mathml/opdict.py from MathML Core, W3C Candidate\n")
w.write("// Recommendation Snapshot 24 June 2025, appendix B.1. DO NOT EDIT.\n\n")
w.write("package layout\n\n")
w.write("// mathOpTwoASCII is Operators_2_ascii_chars (figure 24): the two-character\n")
w.write("// operators, each read as U+0320 plus its index.\n")
w.write("var mathOpTwoASCII = [...]string{\n")
for s in ascii2:
    w.write("\t%s,\n" % ('"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'))
w.write("}\n\n")
for cat, name in (("L", "mathOpCategoryL"), ("M", "mathOpCategoryM")):
    form, cps = cats[cat]
    w.write("// %s is category %s's operators, in %s form (figure 25), whose\n" % (name, cat, form))
    w.write("// category has no encoding in figure 27.\n")
    w.write("var %s = [...]rune{%s}\n\n" % (name, ", ".join("0x%04X" % c for c in cps)))
w.write("// mathOpEntries is figure 27: each entry's low fourteen bits are a key and\n")
w.write("// its top four the category's encoding, sorted by key.\n")
w.write("var mathOpEntries = [...]uint16{\n")
for i in range(0, len(fig27), 8):
    w.write("\t" + ", ".join("0x%04X" % e for e in fig27[i:i + 8]) + ",\n")
w.write("}\n\n")
w.write("// mathOpInlineAxis is figure 28: the characters whose intrinsic stretch axis\n")
w.write("// is inline, sorted.\n")
w.write("var mathOpInlineAxis = [...]rune{\n")
for i in range(0, len(axis), 8):
    w.write("\t" + ", ".join("0x%04X" % c for c in axis[i:i + 8]) + ",\n")
w.write("}\n")
w.close()

rows = re.findall(r"\| (?:String \S+ )?(?:(?!U\+)\S+ )?((?:U\+[0-9A-F]+ ?)+)\| (block|inline) \| (infix|prefix|postfix) \| (\S+) \| (\S+) \| ([^\n|]*)", text)
t = open(out_txt, "w", encoding="utf-8")
t.write("# MathML Core, W3C Candidate Recommendation Snapshot 24 June 2025,\n")
t.write("# appendix B.2, the operator dictionary in human-readable form, transcribed\n")
t.write("# by testdata/mathml/opdict.py. DO NOT EDIT.\n")
t.write("#\n")
t.write("# code points (space-separated), stretch axis, form, lspace, rspace, properties\n")
n = 0
for cps, axis_, form, lsp, rsp, props in rows:
    props = " ".join(w_ for w_ in props.split() if w_ != "N/A")
    t.write("%s\t%s\t%s\t%s\t%s\t%s\n" % (cps.strip(), axis_, form, lsp, rsp, props))
    n += 1
t.close()
print("B.2 rows:", n)
