// Command gencasing generates Unicode's full case mappings — the ones that turn
// one character into more than one — from Unicode's own SpecialCasing.txt.
//
// Go's strings.ToUpper and its neighbours apply the *simple* mappings of
// UnicodeData.txt, which are one character to one character by construction. The
// case of a great deal of ordinary text is not: "straße" uppercases to "STRASSE"
// in every dictionary and every browser, and a one-to-one mapping cannot say so,
// so Go leaves the ß alone and produces "STRAßE". CSS Text §2.1.1 asks for the
// full mappings by name — "the Unicode Default Case Conversion algorithm" — and
// this is the table they need.
//
// SpecialCasing.txt states each mapping as
//
//	<code>; <lower>; <title>; <upper>; (<condition>;)? # <name>
//
// and the conditional entries are left out here, for two different reasons.
// Three of the conditions are language tags — Turkish and Azeri's dotted and
// dotless i, Lithuanian's retained dot — and a language-tailored mapping needs
// the element's language, which is a question about the document rather than
// about a character. The fourth is Final_Sigma, which needs the characters
// around the one being mapped: a lowercase sigma ending a word is ς and one
// inside a word is σ. Both are real and both are missing; neither is a table of
// this shape, and pretending otherwise would apply a Turkish rule to English.
//
// An entry is emitted only where Unicode's full mapping differs from the simple
// mapping Go already applies, so the table is the override and nothing more.
// That is also why it is generated rather than typed: the file holds a hundred
// of these, nearly all Greek, and every one of them is a letter somebody's name
// is spelled with.
//
//	go run ./cmd/gencasing <SpecialCasing.txt> > paragraph/casingtable.go
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// entry is one character's full mapping in one of the three cases.
type entry struct {
	r rune
	s string
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gencasing <SpecialCasing.txt>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	version := "unknown"
	var lower, title, upper []entry
	var conditional int

	sc := bufio.NewScanner(f)
	for line := 1; sc.Scan(); line++ {
		text := sc.Text()
		// The version is in the first comment line, as "SpecialCasing-17.0.0.txt".
		if i := strings.Index(text, "SpecialCasing-"); i >= 0 && version == "unknown" {
			if j := strings.Index(text[i:], ".txt"); j > 0 {
				version = strings.TrimSuffix(text[i+len("SpecialCasing-"):i+j], ".txt")
			}
		}
		if i := strings.IndexByte(text, '#'); i >= 0 {
			text = text[:i]
		}
		fields := strings.Split(text, ";")
		// Four fields and a trailing empty one from the final semicolon. A fifth
		// non-empty field is a condition.
		if len(fields) < 5 || strings.TrimSpace(fields[0]) == "" {
			continue
		}
		if len(fields) > 5 && strings.TrimSpace(fields[4]) != "" {
			conditional++
			continue
		}
		r := parseRune(fields[0], line)
		for i, into := range []*[]entry{&lower, &title, &upper} {
			full := parseRunes(fields[i+1], line)
			simple := string([]rune{[]func(rune) rune{
				unicode.ToLower, unicode.ToTitle, unicode.ToUpper,
			}[i](r)})
			if full != simple {
				*into = append(*into, entry{r, full})
			}
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/gencasing from Unicode's SpecialCasing.txt.
// DO NOT EDIT.

package paragraph

// The characters whose case is not one character. Unicode %s.
//
// Each table holds the mappings SpecialCasing.txt states unconditionally and
// that differ from the simple mapping Go applies: %d lowercased, %d titlecased,
// %d uppercased. The %d conditional entries of the file are left out and are
// described in cmd/gencasing. The tables are sorted by character, and
// texttransform.go decides what to do with them.

// fullCase is one character's mapping, as a string because that is the point.
type fullCase struct {
	r rune
	s string
}
`, version, len(lower), len(title), len(upper), conditional)

	for _, t := range []struct {
		name, what string
		list       []entry
	}{
		{"fullLowercase", "lowercased", lower},
		{"fullTitlecase", "titlecased", title},
		{"fullUppercase", "uppercased", upper},
	} {
		sort.Slice(t.list, func(i, j int) bool { return t.list[i].r < t.list[j].r })
		fmt.Fprintf(&b, "\n// %s: what these characters become when %s.\nvar %s = [...]fullCase{\n",
			t.name, t.what, t.name)
		for _, e := range t.list {
			fmt.Fprintf(&b, "\t{%#04X, %q}, // %s\n", e.r, e.s, runeName(e.r))
		}
		b.WriteString("}\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "generated source does not parse:", err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}

// runeName labels a row with the character itself, so a reader can see what the
// table is about without a code chart. The character is quoted because several
// of them are combining marks that would otherwise attach to the comment.
func runeName(r rune) string {
	return strconv.QuoteRune(r)
}

func parseRune(field string, line int) rune {
	v, err := strconv.ParseUint(strings.TrimSpace(field), 16, 32)
	if err != nil {
		fmt.Fprintf(os.Stderr, "line %d: %v\n", line, err)
		os.Exit(1)
	}
	return rune(v)
}

func parseRunes(field string, line int) string {
	var out []rune
	for _, f := range strings.Fields(field) {
		out = append(out, parseRune(f, line))
	}
	return string(out)
}
