// Code generated by cmd/genphrase from BudouX's ja.json.
// DO NOT EDIT.

package paragraph

// The licence the model is under, copied from its own repository. See
// cmd/genphrase for why it is here in full rather than summarised.
//
//
//                                  Apache License
//                            Version 2.0, January 2004
//                         http://www.apache.org/licenses/
//
//    TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
//
//    1. Definitions.
//
//       "License" shall mean the terms and conditions for use, reproduction,
//       and distribution as defined by Sections 1 through 9 of this document.
//
//       "Licensor" shall mean the copyright owner or entity authorized by
//       the copyright owner that is granting the License.
//
//       "Legal Entity" shall mean the union of the acting entity and all
//       other entities that control, are controlled by, or are under common
//       control with that entity. For the purposes of this definition,
//       "control" means (i) the power, direct or indirect, to cause the
//       direction or management of such entity, whether by contract or
//       otherwise, or (ii) ownership of fifty percent (50%) or more of the
//       outstanding shares, or (iii) beneficial ownership of such entity.
//
//       "You" (or "Your") shall mean an individual or Legal Entity
//       exercising permissions granted by this License.
//
//       "Source" form shall mean the preferred form for making modifications,
//       including but not limited to software source code, documentation
//       source, and configuration files.
//
//       "Object" form shall mean any form resulting from mechanical
//       transformation or translation of a Source form, including but
//       not limited to compiled object code, generated documentation,
//       and conversions to other media types.
//
//       "Work" shall mean the work of authorship, whether in Source or
//       Object form, made available under the License, as indicated by a
//       copyright notice that is included in or attached to the work
//       (an example is provided in the Appendix below).
//
//       "Derivative Works" shall mean any work, whether in Source or Object
//       form, that is based on (or derived from) the Work and for which the
//       editorial revisions, annotations, elaborations, or other modifications
//       represent, as a whole, an original work of authorship. For the purposes
//       of this License, Derivative Works shall not include works that remain
//       separable from, or merely link (or bind by name) to the interfaces of,
//       the Work and Derivative Works thereof.
//
//       "Contribution" shall mean any work of authorship, including
//       the original version of the Work and any modifications or additions
//       to that Work or Derivative Works thereof, that is intentionally
//       submitted to Licensor for inclusion in the Work by the copyright owner
//       or by an individual or Legal Entity authorized to submit on behalf of
//       the copyright owner. For the purposes of this definition, "submitted"
//       means any form of electronic, verbal, or written communication sent
//       to the Licensor or its representatives, including but not limited to
//       communication on electronic mailing lists, source code control systems,
//       and issue tracking systems that are managed by, or on behalf of, the
//       Licensor for the purpose of discussing and improving the Work, but
//       excluding communication that is conspicuously marked or otherwise
//       designated in writing by the copyright owner as "Not a Contribution."
//
//       "Contributor" shall mean Licensor and any individual or Legal Entity
//       on behalf of whom a Contribution has been received by Licensor and
//       subsequently incorporated within the Work.
//
//    2. Grant of Copyright License. Subject to the terms and conditions of
//       this License, each Contributor hereby grants to You a perpetual,
//       worldwide, non-exclusive, no-charge, royalty-free, irrevocable
//       copyright license to reproduce, prepare Derivative Works of,
//       publicly display, publicly perform, sublicense, and distribute the
//       Work and such Derivative Works in Source or Object form.
//
//    3. Grant of Patent License. Subject to the terms and conditions of
//       this License, each Contributor hereby grants to You a perpetual,
//       worldwide, non-exclusive, no-charge, royalty-free, irrevocable
//       (except as stated in this section) patent license to make, have made,
//       use, offer to sell, sell, import, and otherwise transfer the Work,
//       where such license applies only to those patent claims licensable
//       by such Contributor that are necessarily infringed by their
//       Contribution(s) alone or by combination of their Contribution(s)
//       with the Work to which such Contribution(s) was submitted. If You
//       institute patent litigation against any entity (including a
//       cross-claim or counterclaim in a lawsuit) alleging that the Work
//       or a Contribution incorporated within the Work constitutes direct
//       or contributory patent infringement, then any patent licenses
//       granted to You under this License for that Work shall terminate
//       as of the date such litigation is filed.
//
//    4. Redistribution. You may reproduce and distribute copies of the
//       Work or Derivative Works thereof in any medium, with or without
//       modifications, and in Source or Object form, provided that You
//       meet the following conditions:
//
//       (a) You must give any other recipients of the Work or
//           Derivative Works a copy of this License; and
//
//       (b) You must cause any modified files to carry prominent notices
//           stating that You changed the files; and
//
//       (c) You must retain, in the Source form of any Derivative Works
//           that You distribute, all copyright, patent, trademark, and
//           attribution notices from the Source form of the Work,
//           excluding those notices that do not pertain to any part of
//           the Derivative Works; and
//
//       (d) If the Work includes a "NOTICE" text file as part of its
//           distribution, then any Derivative Works that You distribute must
//           include a readable copy of the attribution notices contained
//           within such NOTICE file, excluding those notices that do not
//           pertain to any part of the Derivative Works, in at least one
//           of the following places: within a NOTICE text file distributed
//           as part of the Derivative Works; within the Source form or
//           documentation, if provided along with the Derivative Works; or,
//           within a display generated by the Derivative Works, if and
//           wherever such third-party notices normally appear. The contents
//           of the NOTICE file are for informational purposes only and
//           do not modify the License. You may add Your own attribution
//           notices within Derivative Works that You distribute, alongside
//           or as an addendum to the NOTICE text from the Work, provided
//           that such additional attribution notices cannot be construed
//           as modifying the License.
//
//       You may add Your own copyright statement to Your modifications and
//       may provide additional or different license terms and conditions
//       for use, reproduction, or distribution of Your modifications, or
//       for any such Derivative Works as a whole, provided Your use,
//       reproduction, and distribution of the Work otherwise complies with
//       the conditions stated in this License.
//
//    5. Submission of Contributions. Unless You explicitly state otherwise,
//       any Contribution intentionally submitted for inclusion in the Work
//       by You to the Licensor shall be under the terms and conditions of
//       this License, without any additional terms or conditions.
//       Notwithstanding the above, nothing herein shall supersede or modify
//       the terms of any separate license agreement you may have executed
//       with Licensor regarding such Contributions.
//
//    6. Trademarks. This License does not grant permission to use the trade
//       names, trademarks, service marks, or product names of the Licensor,
//       except as required for reasonable and customary use in describing the
//       origin of the Work and reproducing the content of the NOTICE file.
//
//    7. Disclaimer of Warranty. Unless required by applicable law or
//       agreed to in writing, Licensor provides the Work (and each
//       Contributor provides its Contributions) on an "AS IS" BASIS,
//       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
//       implied, including, without limitation, any warranties or conditions
//       of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
//       PARTICULAR PURPOSE. You are solely responsible for determining the
//       appropriateness of using or redistributing the Work and assume any
//       risks associated with Your exercise of permissions under this License.
//
//    8. Limitation of Liability. In no event and under no legal theory,
//       whether in tort (including negligence), contract, or otherwise,
//       unless required by applicable law (such as deliberate and grossly
//       negligent acts) or agreed to in writing, shall any Contributor be
//       liable to You for damages, including any direct, indirect, special,
//       incidental, or consequential damages of any character arising as a
//       result of this License or out of the use or inability to use the
//       Work (including but not limited to damages for loss of goodwill,
//       work stoppage, computer failure or malfunction, or any and all
//       other commercial damages or losses), even if such Contributor
//       has been advised of the possibility of such damages.
//
//    9. Accepting Warranty or Additional Liability. While redistributing
//       the Work or Derivative Works thereof, You may choose to offer,
//       and charge a fee for, acceptance of support, warranty, indemnity,
//       or other liability obligations and/or rights consistent with this
//       License. However, in accepting such obligations, You may act only
//       on Your own behalf and on Your sole responsibility, not on behalf
//       of any other Contributor, and only if You agree to indemnify,
//       defend, and hold each Contributor harmless for any liability
//       incurred by, or claims asserted against, such Contributor by reason
//       of your accepting any such warranty or additional liability.
//
//    END OF TERMS AND CONDITIONS
//
//    APPENDIX: How to apply the Apache License to your work.
//
//       To apply the Apache License to your work, attach the following
//       boilerplate notice, with the fields enclosed by brackets "[]"
//       replaced with your own identifying information. (Don't include
//       the brackets!)  The text should be enclosed in the appropriate
//       comment syntax for the file format. We also recommend that a
//       file or class name and description of purpose be included on the
//       same "printed page" as the copyright notice for easier
//       identification within third-party archives.
//
//    Copyright [yyyy] [name of copyright owner]
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// japanesePhraseFeatures is the model, one feature per line: the group it belongs to,
// the characters it is about, and the weight they carry, tab separated.
//
// 1630 features over 13 groups, the longest 3 characters.
const japanesePhraseFeatures = `
UW1	]	-25
UW1	、	18
UW1	。	-26
UW1	」	-119
UW1	『	-555
UW1	い	-138
UW1	う	103
UW1	え	-105
UW1	か	-187
UW1	が	-210
UW1	き	-8
UW1	く	165
UW1	こ	160
UW1	ざ	100
UW1	し	-22
UW1	す	202
UW1	そ	183
UW1	た	-112
UW1	ち	243
UW1	っ	198
UW1	つ	315
UW1	て	146
UW1	で	-289
UW1	と	124
UW1	ど	197
UW1	な	-212
UW1	に	-390
UW1	ね	-51
UW1	の	67
UW1	は	-176
UW1	も	13
UW1	や	-248
UW1	よ	87
UW1	り	-106
UW1	る	-82
UW1	れ	118
UW1	ろ	336
UW1	を	-4
UW1	ん	204
UW1	イ	-459
UW1	オ	507
UW1	ク	-4
UW1	ケ	-8
UW1	ス	-209
UW1	タ	247
UW1	ッ	426
UW1	ニ	20
UW1	バ	394
UW1	プ	-787
UW1	メ	422
UW1	ャ	280
UW1	リ	339
UW1	ン	17
UW1	・	52
UW1	上	-140
UW1	京	-106
UW1	人	-65
UW1	何	169
UW1	作	114
UW1	個	-228
UW1	内	-171
UW1	効	642
UW1	十	-269
UW1	取	106
UW1	右	202
UW1	基	-37
UW1	壊	-428
UW1	大	276
UW1	始	733
UW1	安	-460
UW1	小	284
UW1	少	-110
UW1	携	-314
UW1	撮	-122
UW1	新	159
UW1	日	25
UW1	明	905
UW1	時	-212
UW1	機	118
UW1	水	173
UW1	生	-4
UW1	知	91
UW1	積	-93
UW1	自	371
UW1	苦	-506
UW1	行	-36
UW1	見	231
UW1	話	-147
UW1	認	-245
UW1	議	34
UW1	豊	252
UW1	進	156
UW1	長	668
UW1	間	281
UW1	！	68
UW1	．	-438
UW1	０	234
UW1	２	69
UW1	３	-303
UW1	［	-544
UW1	ｏ	-12
UW2	?	-408
UW2	]	-173
UW2	…	239
UW2	★	-399
UW2	、	-1540
UW2	。	-1584
UW2	々	206
UW2	「	-347
UW2	」	209
UW2	『	-228
UW2	あ	-194
UW2	い	-145
UW2	う	-611
UW2	お	-1202
UW2	か	-9
UW2	が	-837
UW2	き	-115
UW2	く	-729
UW2	ぐ	-455
UW2	け	159
UW2	げ	8
UW2	こ	-30
UW2	ご	-501
UW2	さ	708
UW2	し	200
UW2	す	413
UW2	ぜ	931
UW2	そ	-483
UW2	た	-274
UW2	だ	372
UW2	っ	127
UW2	つ	-595
UW2	て	-939
UW2	で	-1025
UW2	と	-1218
UW2	ど	-234
UW2	な	-420
UW2	に	-1161
UW2	ね	354
UW2	の	-942
UW2	は	-1052
UW2	ば	-327
UW2	ぱ	267
UW2	ひ	-2178
UW2	ぶ	85
UW2	ほ	708
UW2	ま	338
UW2	み	-120
UW2	め	65
UW2	も	-961
UW2	や	-625
UW2	ゆ	805
UW2	ら	-70
UW2	り	-229
UW2	る	-407
UW2	れ	-90
UW2	ろ	-200
UW2	わ	317
UW2	を	-2488
UW2	ん	250
UW2	ア	-29
UW2	イ	-161
UW2	グ	-454
UW2	ケ	-522
UW2	サ	-568
UW2	シ	-433
UW2	ジ	-135
UW2	デ	-497
UW2	ド	42
UW2	ノ	495
UW2	バ	426
UW2	パ	668
UW2	メ	-40
UW2	ラ	-534
UW2	ル	47
UW2	レ	-113
UW2	ー	216
UW2	一	1244
UW2	三	429
UW2	下	296
UW2	世	-338
UW2	人	75
UW2	介	97
UW2	以	2491
UW2	作	-19
UW2	先	378
UW2	全	1268
UW2	取	-414
UW2	同	511
UW2	味	500
UW2	和	646
UW2	団	696
UW2	場	274
UW2	境	-297
UW2	多	560
UW2	大	152
UW2	奇	205
UW2	如	479
UW2	安	-94
UW2	家	142
UW2	容	1349
UW2	少	606
UW2	我	-831
UW2	手	1408
UW2	敗	159
UW2	文	116
UW2	新	-139
UW2	早	222
UW2	昔	260
UW2	是	440
UW2	最	225
UW2	本	556
UW2	格	548
UW2	案	141
UW2	次	-183
UW2	残	151
UW2	毎	1534
UW2	水	732
UW2	法	1473
UW2	特	868
UW2	甘	11
UW2	生	87
UW2	用	-25
UW2	百	-157
UW2	目	-759
UW2	直	295
UW2	知	-961
UW2	空	-34
UW2	立	-473
UW2	級	771
UW2	素	-443
UW2	結	2129
UW2	能	348
UW2	良	243
UW2	落	-546
UW2	裏	-14
UW2	見	-308
UW2	言	-5
UW2	許	538
UW2	買	-17
UW2	車	84
UW2	選	185
UW2	関	1438
UW2	随	1550
UW2	電	268
UW2	食	261
UW2	鹿	-135
UW2	，	-526
UW2	０	115
UW2	１	180
UW2	２	-241
UW2	３	-291
UW2	４	326
UW2	５	-128
UW2	？	-621
UW2	Ｈ	-144
UW2	Ｐ	-648
UW2	［	-89
UW2	］	-262
UW2	＾	102
UW3	?	4664
UW3	[	-1045
UW3	]	3594
UW3	”	1246
UW3	…	3125
UW3	★	2952
UW3	☆	3592
UW3	♪	2801
UW3	　	451
UW3	、	5474
UW3	。	7331
UW3	々	2067
UW3	「	-1977
UW3	」	1822
UW3	『	-837
UW3	』	284
UW3	】	480
UW3	〜	956
UW3	ぁ	1694
UW3	あ	1168
UW3	い	2058
UW3	う	2494
UW3	え	910
UW3	お	-2026
UW3	か	2214
UW3	が	4577
UW3	き	484
UW3	く	2935
UW3	ぐ	3001
UW3	け	117
UW3	こ	183
UW3	ご	-1325
UW3	さ	-84
UW3	し	407
UW3	じ	533
UW3	す	1109
UW3	ず	1808
UW3	せ	688
UW3	ぞ	1024
UW3	た	2639
UW3	だ	1055
UW3	ち	592
UW3	っ	-1794
UW3	つ	1371
UW3	て	2767
UW3	で	3706
UW3	と	3626
UW3	ど	1749
UW3	な	2949
UW3	に	4335
UW3	ぬ	2615
UW3	ね	723
UW3	の	4438
UW3	は	4653
UW3	ば	2526
UW3	ぱ	723
UW3	ぶ	1284
UW3	へ	2276
UW3	ま	-43
UW3	み	505
UW3	む	1491
UW3	も	3679
UW3	ゃ	1311
UW3	や	2604
UW3	よ	608
UW3	ら	1690
UW3	り	1280
UW3	る	3301
UW3	れ	190
UW3	ろ	1311
UW3	わ	-220
UW3	を	6140
UW3	ん	1063
UW3	ア	-1107
UW3	イ	-908
UW3	カ	-553
UW3	ク	110
UW3	シ	-735
UW3	ジ	-176
UW3	ス	-861
UW3	タ	-162
UW3	ッ	-2059
UW3	テ	-147
UW3	デ	-279
UW3	ト	-93
UW3	ド	-561
UW3	ニ	-140
UW3	バ	-268
UW3	ビ	-4
UW3	フ	-1375
UW3	プ	-1102
UW3	モ	-107
UW3	ラ	-281
UW3	レ	-180
UW3	ロ	-757
UW3	ン	-563
UW3	・	1048
UW3	ー	-197
UW3	上	625
UW3	不	-86
UW3	中	1200
UW3	京	-1379
UW3	人	341
UW3	今	1154
UW3	代	-63
UW3	以	-984
UW3	体	891
UW3	作	-90
UW3	光	-318
UW3	入	-192
UW3	分	1190
UW3	別	234
UW3	前	192
UW3	区	924
UW3	台	499
UW3	味	546
UW3	品	129
UW3	場	-68
UW3	変	779
UW3	夜	1518
UW3	大	-1219
UW3	始	-93
UW3	子	-211
UW3	学	-397
UW3	年	339
UW3	度	1238
UW3	後	1303
UW3	意	-122
UW3	感	738
UW3	所	345
UW3	技	209
UW3	択	970
UW3	料	-412
UW3	斤	509
UW3	新	-866
UW3	方	888
UW3	日	830
UW3	昔	1709
UW3	時	185
UW3	最	-519
UW3	月	112
UW3	果	361
UW3	機	-217
UW3	段	56
UW3	水	342
UW3	然	1170
UW3	現	-76
UW3	生	-55
UW3	用	-416
UW3	番	289
UW3	発	-399
UW3	的	430
UW3	皆	969
UW3	秋	1113
UW3	程	505
UW3	空	1563
UW3	笑	3650
UW3	系	687
UW3	素	-168
UW3	能	-29
UW3	自	-336
UW3	色	486
UW3	行	-355
UW3	観	-957
UW3	超	1609
UW3	週	143
UW3	選	-102
UW3	部	542
UW3	都	-296
UW3	開	-90
UW3	間	958
UW3	電	-1431
UW3	題	809
UW3	！	4003
UW3	）	3330
UW3	，	4119
UW3	．	2432
UW3	０	-805
UW3	１	-1318
UW3	５	-59
UW3	：	381
UW3	？	4334
UW3	［	-768
UW3	］	2440
UW3	ｏ	-464
UW4	(	654
UW4	?	-4390
UW4	[	3554
UW4	]	-1443
UW4	”	-1348
UW4	…	-3150
UW4	★	-844
UW4	☆	-1767
UW4	♪	-2039
UW4	　	-1382
UW4	、	-8150
UW4	。	-7835
UW4	「	2346
UW4	」	-6475
UW4	『	982
UW4	』	-5072
UW4	【	585
UW4	〜	-1764
UW4	ぁ	-1624
UW4	あ	255
UW4	ぃ	-4
UW4	い	-1550
UW4	う	-2712
UW4	え	-2262
UW4	お	892
UW4	か	-2915
UW4	が	-4054
UW4	き	-1830
UW4	ぎ	-1605
UW4	く	-3063
UW4	ぐ	-1842
UW4	け	-3754
UW4	げ	-906
UW4	こ	-507
UW4	ご	293
UW4	さ	-1760
UW4	ざ	-1085
UW4	し	-1935
UW4	じ	-2491
UW4	す	-1699
UW4	ず	-2065
UW4	せ	-1969
UW4	ぜ	-1481
UW4	そ	429
UW4	ぞ	-1226
UW4	た	-2016
UW4	だ	-2260
UW4	ち	-2389
UW4	っ	-4802
UW4	つ	-1268
UW4	づ	-795
UW4	て	-3970
UW4	で	-3133
UW4	と	-3243
UW4	ど	-885
UW4	な	-2126
UW4	に	-4664
UW4	ね	-2484
UW4	の	-4526
UW4	は	-3843
UW4	ば	-2646
UW4	ひ	541
UW4	び	-1816
UW4	ふ	-16
UW4	ぶ	-1703
UW4	へ	-1023
UW4	べ	-3191
UW4	ほ	-328
UW4	ぼ	-972
UW4	ま	-1687
UW4	み	-907
UW4	む	-1336
UW4	め	-2463
UW4	も	-2930
UW4	ゃ	-2623
UW4	や	-1377
UW4	ゆ	-825
UW4	ょ	-2028
UW4	よ	-1377
UW4	ら	-5271
UW4	り	-4632
UW4	る	-5856
UW4	れ	-4518
UW4	ろ	-3124
UW4	わ	-1719
UW4	を	-5179
UW4	ん	-4492
UW4	イ	-143
UW4	エ	271
UW4	オ	68
UW4	カ	231
UW4	ク	-240
UW4	グ	-141
UW4	コ	64
UW4	ジ	-8
UW4	ス	-149
UW4	タ	-298
UW4	ッ	-2340
UW4	デ	615
UW4	ト	-346
UW4	ド	-300
UW4	ニ	-238
UW4	バ	308
UW4	ビ	-158
UW4	フ	-334
UW4	ミ	-33
UW4	ム	-77
UW4	ュ	-807
UW4	リ	-1047
UW4	ル	-1129
UW4	ロ	-279
UW4	ン	-2274
UW4	・	-1475
UW4	ー	-2954
UW4	一	569
UW4	不	696
UW4	二	611
UW4	京	392
UW4	人	514
UW4	今	1470
UW4	他	181
UW4	代	-114
UW4	住	8
UW4	何	717
UW4	使	851
UW4	例	106
UW4	修	4
UW4	僕	1126
UW4	入	129
UW4	全	87
UW4	公	376
UW4	切	-376
UW4	制	794
UW4	券	-37
UW4	効	71
UW4	動	-34
UW4	参	98
UW4	友	102
UW4	取	-531
UW4	合	-1661
UW4	品	-202
UW4	四	276
UW4	回	-1175
UW4	場	401
UW4	声	85
UW4	夏	522
UW4	多	1189
UW4	大	654
UW4	姿	158
UW4	実	60
UW4	小	747
UW4	少	273
UW4	帯	-1165
UW4	年	-375
UW4	広	493
UW4	度	-229
UW4	彼	83
UW4	心	12
UW4	思	1144
UW4	情	-106
UW4	手	154
UW4	換	-690
UW4	携	168
UW4	新	311
UW4	方	-465
UW4	日	280
UW4	春	8
UW4	時	454
UW4	書	572
UW4	最	996
UW4	有	295
UW4	服	869
UW4	本	-124
UW4	来	130
UW4	東	710
UW4	森	-428
UW4	楽	372
UW4	機	-118
UW4	気	95
UW4	水	329
UW4	無	336
UW4	煙	2026
UW4	父	403
UW4	物	-311
UW4	特	1097
UW4	狭	264
UW4	甘	151
UW4	用	-630
UW4	的	-991
UW4	真	-503
UW4	祭	558
UW4	私	1972
UW4	秋	127
UW4	空	1226
UW4	笑	-3433
UW4	系	259
UW4	続	-656
UW4	綺	2459
UW4	美	260
UW4	聞	199
UW4	能	-732
UW4	自	699
UW4	臭	1197
UW4	良	87
UW4	行	434
UW4	街	558
UW4	表	166
UW4	見	1092
UW4	言	351
UW4	話	371
UW4	誰	1040
UW4	買	225
UW4	足	704
UW4	込	-604
UW4	返	-364
UW4	通	-66
UW4	間	-755
UW4	青	798
UW4	鞍	112
UW4	頑	176
UW4	食	294
UW4	高	107
UW4	！	-5229
UW4	（	2718
UW4	）	-4245
UW4	，	-4881
UW4	．	-3345
UW4	０	-431
UW4	１	1027
UW4	２	820
UW4	３	435
UW4	４	-215
UW4	？	-5720
UW4	Ｓ	-143
UW4	［	1713
UW4	］	-1515
UW4	＾	-122
UW4	ｏ	-633
UW5	[	-434
UW5	…	-209
UW5	、	-1080
UW5	。	-2134
UW5	々	237
UW5	」	-1096
UW5	あ	-394
UW5	い	360
UW5	う	444
UW5	え	727
UW5	か	195
UW5	が	-597
UW5	き	1101
UW5	ぎ	320
UW5	く	352
UW5	こ	125
UW5	さ	-303
UW5	ざ	335
UW5	し	-331
UW5	じ	744
UW5	す	-696
UW5	ず	812
UW5	せ	-438
UW5	そ	-665
UW5	た	-31
UW5	だ	-485
UW5	ち	522
UW5	っ	1246
UW5	つ	1095
UW5	て	220
UW5	で	-961
UW5	と	-894
UW5	ど	-9
UW5	な	-632
UW5	に	-767
UW5	の	-889
UW5	は	-1048
UW5	び	609
UW5	へ	-282
UW5	べ	1996
UW5	ぼ	1438
UW5	ま	-98
UW5	む	810
UW5	め	528
UW5	も	-205
UW5	よ	-284
UW5	ら	181
UW5	り	187
UW5	る	514
UW5	れ	462
UW5	ろ	-67
UW5	わ	588
UW5	を	-806
UW5	ん	946
UW5	イ	124
UW5	オ	-25
UW5	グ	-120
UW5	ス	-271
UW5	デ	-192
UW5	ト	-388
UW5	バ	-71
UW5	ャ	51
UW5	ュ	-257
UW5	ラ	547
UW5	ル	-699
UW5	ロ	25
UW5	ン	-260
UW5	・	-945
UW5	一	-197
UW5	丈	333
UW5	上	-402
UW5	京	78
UW5	体	-1449
UW5	作	365
UW5	使	-1252
UW5	先	-797
UW5	利	781
UW5	力	339
UW5	動	1439
UW5	器	-220
UW5	回	193
UW5	大	-275
UW5	定	12
UW5	寺	-278
UW5	帯	334
UW5	年	968
UW5	当	628
UW5	思	-359
UW5	日	575
UW5	景	340
UW5	本	178
UW5	水	-443
UW5	的	-264
UW5	目	-46
UW5	能	88
UW5	葉	186
UW5	行	-34
UW5	要	33
UW5	見	-57
UW5	言	-236
UW5	越	-763
UW5	開	78
UW5	電	-205
UW5	面	34
UW5	顔	-329
UW5	！	-311
UW5	．	-224
UW5	１	-114
UW5	２	-134
UW5	？	-240
UW5	Ｎ	786
UW5	］	-422
UW6	。	-308
UW6	」	-190
UW6	い	346
UW6	う	237
UW6	お	-401
UW6	か	312
UW6	が	369
UW6	ぎ	604
UW6	く	131
UW6	け	-219
UW6	こ	119
UW6	さ	944
UW6	し	463
UW6	じ	116
UW6	ず	-131
UW6	せ	-301
UW6	そ	54
UW6	た	27
UW6	だ	-42
UW6	っ	486
UW6	つ	696
UW6	て	-65
UW6	で	160
UW6	と	34
UW6	ど	60
UW6	な	226
UW6	に	327
UW6	の	138
UW6	は	202
UW6	ば	40
UW6	ぱ	1094
UW6	び	59
UW6	ま	413
UW6	み	702
UW6	め	913
UW6	も	109
UW6	や	638
UW6	ょ	-238
UW6	よ	267
UW6	り	513
UW6	る	182
UW6	れ	167
UW6	ろ	464
UW6	わ	268
UW6	を	154
UW6	ん	349
UW6	カ	194
UW6	ク	-300
UW6	グ	789
UW6	コ	192
UW6	シ	-177
UW6	ス	27
UW6	タ	331
UW6	デ	-202
UW6	パ	-559
UW6	ピ	33
UW6	ブ	29
UW6	ュ	224
UW6	ル	188
UW6	ン	-343
UW6	・	-200
UW6	ー	-162
UW6	亭	407
UW6	人	-95
UW6	付	53
UW6	供	-427
UW6	出	534
UW6	制	372
UW6	地	530
UW6	場	-573
UW6	学	-426
UW6	家	-115
UW6	寺	325
UW6	思	-178
UW6	新	-4
UW6	方	-77
UW6	日	36
UW6	最	-248
UW6	来	-111
UW6	気	563
UW6	水	898
UW6	画	407
UW6	的	366
UW6	空	972
UW6	自	216
UW6	見	-162
UW6	言	-223
UW6	込	474
UW6	返	1149
UW6	送	-1624
UW6	遊	-497
UW6	過	246
UW6	電	358
UW6	０	693
UW6	１	119
UW6	：	586
UW6	］	-115
BW1	、と	308
BW1	、今	805
BW1	、真	4785
BW1	。」	2184
BW1	。・	2850
BW1	」と	261
BW1	あー	1779
BW1	い、	-391
BW1	いい	-393
BW1	いう	530
BW1	いし	148
BW1	いた	151
BW1	いで	-1082
BW1	いと	-291
BW1	いの	-221
BW1	いも	-807
BW1	うえ	425
BW1	うか	240
BW1	うな	592
BW1	うに	-49
BW1	うや	-287
BW1	えば	240
BW1	おで	-3878
BW1	お店	690
BW1	か、	-371
BW1	かき	580
BW1	かけ	-34
BW1	かし	1573
BW1	かも	-1721
BW1	から	1722
BW1	か，	-1339
BW1	が、	1142
BW1	がと	-955
BW1	きた	487
BW1	きの	-962
BW1	くて	727
BW1	くれ	2314
BW1	けど	753
BW1	こう	-168
BW1	ここ	100
BW1	こそ	1536
BW1	こと	-1663
BW1	この	-1192
BW1	ころ	485
BW1	さん	64
BW1	しい	1439
BW1	しか	4
BW1	した	325
BW1	して	-150
BW1	じて	203
BW1	す☆	58
BW1	すい	112
BW1	すが	-69
BW1	すの	-60
BW1	せん	59
BW1	その	-1266
BW1	たい	724
BW1	ただ	1271
BW1	たと	-1187
BW1	たの	-1057
BW1	ため	514
BW1	たら	1203
BW1	たり	4
BW1	た．	1552
BW1	だけ	600
BW1	だし	582
BW1	だん	128
BW1	ちが	-674
BW1	った	226
BW1	っと	-33
BW1	つな	-1587
BW1	て、	9
BW1	てい	-500
BW1	ては	-102
BW1	ても	825
BW1	てる	202
BW1	で…	831
BW1	で、	433
BW1	では	-294
BW1	でも	881
BW1	と、	348
BW1	とい	-78
BW1	とう	147
BW1	とか	1792
BW1	とが	-1312
BW1	とき	2050
BW1	とこ	-63
BW1	とで	1529
BW1	との	460
BW1	とは	-110
BW1	とも	-76
BW1	ない	1248
BW1	なく	334
BW1	なぐ	1197
BW1	なぜ	1651
BW1	など	623
BW1	なら	1187
BW1	なー	37
BW1	には	454
BW1	にも	628
BW1	に水	25
BW1	ねー	307
BW1	のが	916
BW1	ので	225
BW1	のは	1264
BW1	のみ	2935
BW1	のも	124
BW1	の上	743
BW1	の後	977
BW1	の間	1507
BW1	は、	931
BW1	は頭	928
BW1	ぱり	286
BW1	ぶん	673
BW1	べき	989
BW1	ほぼ	149
BW1	まだ	776
BW1	まと	-1866
BW1	まま	2275
BW1	まも	-3453
BW1	まり	470
BW1	めて	147
BW1	める	-175
BW1	もう	1545
BW1	もし	1384
BW1	もの	-627
BW1	もは	-3656
BW1	ゃあ	661
BW1	やく	1335
BW1	やら	986
BW1	よう	-711
BW1	よく	582
BW1	より	1697
BW1	らな	-591
BW1	りと	700
BW1	りは	-290
BW1	りゃ	1760
BW1	ると	91
BW1	るに	-612
BW1	るの	-1335
BW1	れが	-562
BW1	れた	1317
BW1	れて	-371
BW1	れる	60
BW1	ろう	-374
BW1	わけ	398
BW1	んだ	781
BW1	んて	156
BW1	んで	-494
BW1	んな	247
BW1	んに	-1214
BW1	ック	270
BW1	パサ	476
BW1	リー	157
BW1	世の	-645
BW1	人、	-214
BW1	人気	1231
BW1	以上	29
BW1	使い	-992
BW1	使う	89
BW1	全部	695
BW1	分け	593
BW1	効果	1280
BW1	取り	-456
BW1	同じ	1197
BW1	問い	-436
BW1	大変	8
BW1	安に	-718
BW1	寺、	-1144
BW1	少し	1794
BW1	待ち	-469
BW1	思い	-1500
BW1	持て	-79
BW1	是非	377
BW1	普段	718
BW1	晶の	2483
BW1	最近	1892
BW1	本語	178
BW1	気に	-333
BW1	法的	67
BW1	現在	554
BW1	甘味	569
BW1	白い	1354
BW1	的な	365
BW1	知る	-254
BW1	神社	931
BW1	空き	-54
BW1	絶対	443
BW1	舞う	328
BW1	言い	-567
BW1	買い	-753
BW1	離宮	29
BW1	青い	473
BW1	０円	353
BW1	２、	-2026
BW1	４日	102
BW1	＾＾	408
BW1	ｏｒ	446
BW2	、と	-1273
BW2	、な	-323
BW2	、清	-33
BW2	。笑	-1204
BW2	」で	936
BW2	」と	-433
BW2	いい	-928
BW2	いし	-713
BW2	いた	-1271
BW2	いつ	-178
BW2	いと	-940
BW2	いな	-407
BW2	いま	-851
BW2	いも	784
BW2	いよ	-3030
BW2	い合	-1523
BW2	い日	416
BW2	うい	-216
BW2	うご	1924
BW2	うど	-1919
BW2	うや	-1100
BW2	う映	394
BW2	かし	-379
BW2	かな	-357
BW2	がし	72
BW2	がち	-83
BW2	がっ	-488
BW2	がの	29
BW2	が観	-950
BW2	くし	-714
BW2	くだ	-2195
BW2	くな	-1776
BW2	こし	365
BW2	し…	1799
BW2	しい	-305
BW2	した	-768
BW2	すご	-996
BW2	すも	529
BW2	せく	6048
BW2	そこ	-275
BW2	たい	-2164
BW2	たし	-230
BW2	ただ	-1376
BW2	たち	-269
BW2	たと	680
BW2	たな	-80
BW2	たま	-1297
BW2	たも	103
BW2	たよ	-20
BW2	てあ	-2151
BW2	てい	-1546
BW2	てお	-2172
BW2	てき	-2092
BW2	てく	-1211
BW2	てこ	-172
BW2	てみ	-2185
BW2	ても	-606
BW2	てや	-142
BW2	て来	-232
BW2	て欲	-466
BW2	て行	-2250
BW2	であ	-3442
BW2	でい	-203
BW2	でき	-2187
BW2	でし	-1822
BW2	です	-2940
BW2	でな	-1219
BW2	では	-618
BW2	でも	-1946
BW2	とい	180
BW2	とお	-2638
BW2	とか	-1075
BW2	とき	-767
BW2	とこ	-1757
BW2	とと	-657
BW2	とは	-348
BW2	とめ	-460
BW2	とも	-606
BW2	どこ	-794
BW2	ども	-531
BW2	なぁ	-494
BW2	なあ	-1506
BW2	ない	-3413
BW2	なか	-495
BW2	なく	-852
BW2	など	-2282
BW2	にぎ	-250
BW2	にこ	-198
BW2	にし	-486
BW2	にな	-75
BW2	には	-791
BW2	にも	-1394
BW2	のい	303
BW2	のか	-634
BW2	のが	-1144
BW2	のご	-1134
BW2	のだ	-1038
BW2	ので	-1978
BW2	のは	-1264
BW2	のみ	-3030
BW2	のも	-925
BW2	の前	-1526
BW2	の方	159
BW2	の１	-1747
BW2	はあ	-507
BW2	はい	-834
BW2	はじ	-2168
BW2	はず	-582
BW2	ぱな	67
BW2	び上	1661
BW2	もあ	-595
BW2	もう	-171
BW2	もし	-920
BW2	もつ	-361
BW2	もな	-16
BW2	やす	-1370
BW2	よい	-566
BW2	らい	-353
BW2	らな	-254
BW2	らゆ	-1056
BW2	りな	227
BW2	るか	-29
BW2	るが	-80
BW2	るし	-128
BW2	ると	-596
BW2	るな	-264
BW2	るの	-108
BW2	るよ	-228
BW2	れた	-94
BW2	を返	-1669
BW2	グと	780
BW2	ルや	137
BW2	・・	-386
BW2	中さ	322
BW2	中だ	114
BW2	人い	1504
BW2	係な	620
BW2	帯電	-1412
BW2	徴エ	1381
BW2	日と	374
BW2	日本	-309
BW2	本イ	2005
BW2	気な	330
BW2	．９	-24
BW2	］私	-479
BW3	あと	1228
BW3	あふ	84
BW3	あり	115
BW3	ある	-287
BW3	いい	1123
BW3	いう	790
BW3	いか	663
BW3	いた	-26
BW3	いつ	20
BW3	いて	-460
BW3	いま	563
BW3	いら	361
BW3	いる	55
BW3	いろ	404
BW3	うち	552
BW3	うま	3341
BW3	ええ	1084
BW3	おす	397
BW3	おで	1062
BW3	おり	-1380
BW3	かか	1930
BW3	かき	293
BW3	かけ	2176
BW3	かっ	-1165
BW3	かも	-592
BW3	から	-1032
BW3	が、	1559
BW3	がん	1905
BW3	が観	2221
BW3	きま	-605
BW3	きる	-925
BW3	こそ	-557
BW3	こだ	50
BW3	こと	1175
BW3	この	2317
BW3	これ	2270
BW3	ころ	-297
BW3	こん	-92
BW3	ごと	-287
BW3	さあ	662
BW3	さい	-807
BW3	さん	-2110
BW3	し、	-70
BW3	しい	-957
BW3	しか	-210
BW3	しく	-63
BW3	した	907
BW3	して	218
BW3	しま	-296
BW3	しゃ	381
BW3	すか	-409
BW3	すき	240
BW3	すぐ	1632
BW3	すご	1542
BW3	そう	-1883
BW3	そく	-136
BW3	そし	356
BW3	その	2329
BW3	たい	-166
BW3	ただ	293
BW3	たっ	576
BW3	たま	1011
BW3	ため	1069
BW3	だい	46
BW3	だけ	-754
BW3	だろ	-1479
BW3	ちは	-1191
BW3	ちょ	2198
BW3	つい	573
BW3	つき	394
BW3	つけ	355
BW3	つな	1280
BW3	つぶ	642
BW3	で、	1140
BW3	でき	917
BW3	です	-903
BW3	でも	1755
BW3	とい	-754
BW3	とき	2382
BW3	とこ	408
BW3	とっ	875
BW3	とて	2483
BW3	とも	1246
BW3	とら	456
BW3	とり	1101
BW3	と思	-575
BW3	どこ	399
BW3	ない	481
BW3	なか	235
BW3	なく	402
BW3	なさ	208
BW3	なっ	-601
BW3	など	-117
BW3	なに	319
BW3	なら	-409
BW3	なる	316
BW3	なん	292
BW3	にぎ	723
BW3	はし	709
BW3	はじ	2407
BW3	はず	770
BW3	はま	1074
BW3	はる	721
BW3	ひと	380
BW3	ほど	-33
BW3	ぼっ	-1028
BW3	ぼれ	-380
BW3	まぁ	1446
BW3	まし	-943
BW3	ます	-772
BW3	ませ	-117
BW3	まだ	610
BW3	まで	-296
BW3	まと	1846
BW3	まも	279
BW3	みた	-1184
BW3	みろ	115
BW3	みん	529
BW3	もう	2304
BW3	もっ	336
BW3	もつ	721
BW3	もと	1138
BW3	もの	3907
BW3	もら	2822
BW3	もん	1103
BW3	ゆる	-896
BW3	よう	-1314
BW3	よく	1416
BW3	より	-1170
BW3	わか	660
BW3	んで	260
BW3	アプ	55
BW3	デザ	565
BW3	メー	450
BW3	ルー	311
BW3	・・	-1620
BW3	一に	-695
BW3	上が	1264
BW3	以上	-395
BW3	何で	454
BW3	使っ	72
BW3	入れ	90
BW3	入場	413
BW3	出来	-628
BW3	分か	1490
BW3	友人	108
BW3	受け	890
BW3	可能	95
BW3	変え	271
BW3	始ま	217
BW3	当日	2335
BW3	日が	472
BW3	書い	132
BW3	最近	148
BW3	機器	-1682
BW3	祭り	84
BW3	色は	110
BW3	行く	169
BW3	通り	-261
BW3	電話	-44
BW3	電車	82
TW1	、それ	675
TW1	。ただ	16
TW1	。夕方	161
TW1	ありが	-2684
TW1	いとこ	-808
TW1	ういう	20
TW1	おけば	147
TW1	おって	3070
TW1	かった	-96
TW1	かなか	752
TW1	かなり	1990
TW1	が良い	786
TW1	くさん	213
TW1	くらい	189
TW1	ことも	-358
TW1	こんに	-455
TW1	しかし	752
TW1	すきと	-3102
TW1	すごく	312
TW1	そして	174
TW1	その時	2086
TW1	たまた	-714
TW1	だんど	-1554
TW1	っかり	783
TW1	ていく	997
TW1	ていて	254
TW1	でかけ	-656
TW1	できる	396
TW1	で見る	-2977
TW1	という	412
TW1	として	267
TW1	とんど	763
TW1	と思う	16
TW1	ない、	-1607
TW1	ながら	1161
TW1	なって	-94
TW1	なんと	-1121
TW1	にして	-46
TW1	に来て	667
TW1	のうち	148
TW1	のバス	20
TW1	は一つ	-707
TW1	は正直	339
TW1	ひとつ	1367
TW1	ふだん	2004
TW1	ました	-1069
TW1	またま	3831
TW1	まるで	85
TW1	もなく	113
TW1	もはや	2606
TW1	やはり	2033
TW1	ょうど	827
TW1	ょっと	-325
TW1	よいよ	3595
TW1	ような	1127
TW1	る」と	-946
TW1	ろいろ	177
TW1	んでも	128
TW1	んどん	1519
TW1	レベル	366
TW1	・・・	1415
TW1	入れる	260
TW1	十分に	-364
TW1	困った	693
TW1	持って	-1039
TW1	甘えが	-1234
TW2	いい感	-8
TW2	いとこ	-3730
TW2	うにな	-974
TW2	かもし	-8
TW2	からし	556
TW2	からな	-624
TW2	しかな	308
TW2	したこ	-283
TW2	してお	-1405
TW2	そのま	-1448
TW2	その後	-629
TW2	そもそ	-1950
TW2	それ以	261
TW2	ちがう	-1802
TW2	ってこ	-220
TW2	っての	1292
TW2	っとい	-404
TW2	てもい	-1357
TW2	ではあ	-1780
TW2	ではな	-1947
TW2	でもあ	-1421
TW2	でもな	-1053
TW2	という	-25
TW2	とがあ	-1081
TW2	とがで	-200
TW2	とにな	-327
TW2	ともあ	-687
TW2	どんど	-903
TW2	のに対	-259
TW2	まるで	-281
TW2	ものす	-823
TW2	ような	-503
TW2	ようや	-538
TW2	らと言	-1185
TW2	るにつ	-106
TW2	れはそ	-1417
TW2	れるこ	266
TW2	んでい	-1891
TW2	んなこ	-87
TW2	んなん	1024
TW2	分にあ	-2591
TW2	国人が	989
TW2	女の子	-1717
TW2	気に入	-3717
TW3	、そし	-3799
TW3	、また	-825
TW3	」って	906
TW3	ういう	-635
TW3	があっ	109
TW3	くして	-289
TW3	すこと	899
TW3	たこと	-68
TW3	ていう	514
TW3	ている	-2512
TW3	ておき	-625
TW3	てしま	-1783
TW3	てない	-314
TW3	てほし	-994
TW3	であっ	-1154
TW3	である	-911
TW3	といい	-466
TW3	という	530
TW3	といっ	-29
TW3	ところ	-834
TW3	とした	-1399
TW3	として	91
TW3	ととも	-485
TW3	と同時	-1341
TW3	と言っ	-1426
TW3	にする	-20
TW3	にでも	-638
TW3	になっ	-458
TW3	になる	-8
TW3	のこの	-157
TW3	のまま	-494
TW3	のよい	597
TW3	のよう	-1023
TW3	の本は	-1332
TW3	はそれ	-601
TW3	はない	-473
TW3	はまっ	-1300
TW3	ばいい	-1221
TW3	らない	-1576
TW3	ること	-336
TW3	る方は	-700
TW3	ーした	1308
TW3	，それ	-71
TW4	あたり	-4
TW4	ありが	2595
TW4	ありま	-963
TW4	ある。	-583
TW4	あるい	-3230
TW4	あるも	46
TW4	いえば	439
TW4	いかな	448
TW4	いくさ	-203
TW4	いくら	132
TW4	いけな	-428
TW4	いって	-314
TW4	いっぱ	1905
TW4	いまし	-289
TW4	います	-119
TW4	いよい	1454
TW4	いろい	1055
TW4	うどん	2043
TW4	おりに	-451
TW4	おりま	1584
TW4	かけら	645
TW4	かった	-228
TW4	かなり	2324
TW4	が、そ	1483
TW4	くらい	1946
TW4	こと。	569
TW4	ことが	-1192
TW4	ことで	319
TW4	ことに	-1257
TW4	ことは	-267
TW4	ことも	-948
TW4	ことを	358
TW4	これは	1089
TW4	さらに	42
TW4	しかし	2054
TW4	した。	-1506
TW4	してお	1218
TW4	して人	-1146
TW4	しない	213
TW4	しゃべ	1977
TW4	すると	228
TW4	そうで	-738
TW4	そのま	373
TW4	だった	-1408
TW4	だって	1379
TW4	ちがう	2357
TW4	ちなみ	1830
TW4	ってこ	412
TW4	で、そ	1288
TW4	できた	1495
TW4	でも、	468
TW4	でもま	632
TW4	とおり	2028
TW4	とこが	1173
TW4	ところ	3232
TW4	とこ取	-230
TW4	どのよ	3827
TW4	どんど	429
TW4	ない。	218
TW4	ないと	261
TW4	なかな	111
TW4	なんか	476
TW4	なんて	-477
TW4	なんと	1084
TW4	の京都	548
TW4	はじま	343
TW4	はまっ	90
TW4	ひとつ	84
TW4	もはや	3296
TW4	やって	185
TW4	ようで	-254
TW4	ような	-1762
TW4	ように	-955
TW4	ようや	3170
TW4	わけで	-622
TW4	プログ	1692
TW4	メール	47
TW4	京都に	25
TW4	勝手に	850
TW4	可能性	2270
`

// japanesePhraseBias is what a boundary's score starts from, doubled.
//
// BudouX begins each score at minus half the sum of every weight in the model,
// so that a boundary no feature has anything to say about scores below zero and
// is not a boundary. Half of an odd sum is not an integer, so what is kept here
// is the sum itself and the features are counted twice against it — which is
// the same comparison with nothing rounded away.
const japanesePhraseBias = -3224
