// Command gencharprop generates the character properties the engine asks about
// a character that no more specific table answers: every code point's
// General_Category, and four binary properties.
//
// They used to be Go's. package unicode answers IsLetter, IsPunct and In(r, Mn)
// from the release the Go toolchain shipped — 15.0.0 for Go 1.26 — while every
// table beside them was generated from the release the Makefile pins. A
// character Unicode 16 or 17 assigned was a mark to the shaper's tables and
// "not a mark" to the cluster walk around it, a letter to the case tables and
// "not a letter" to the word it was in: U+0897 ARABIC PEPET, the Garay letters
// and digits. Two releases in one engine answer one question two ways, and
// which answer a document got depended on which package happened to ask — and
// on which toolchain built it.
//
// So the questions are answered from the files the rest of the tables are, at
// the release the header names, and nothing in the tree asks package unicode
// a property question; cmd/pinnedunicode_test.go holds it to that.
//
// General_Category is read from UnicodeData.txt. A code point the file does not
// list is unassigned, Cn, and is not in the table; the ranges the file states
// as a First/Last pair are expanded (see cmd/internal/ucd). White_Space and
// Soft_Dotted are read from PropList.txt, and Cased and Case_Ignorable from
// DerivedCoreProperties.txt. Those two are derived from more than the category —
// Case_Ignorable takes in three Word_Break values, Cased the Other_Lowercase
// and Other_Uppercase lists — and reading the derivation rather than repeating
// it is the point. The case mappings are not here: they are paragraph's, from
// cmd/gencasing.
//
//	go run ./cmd/gencharprop -version <X.Y.Z> <UnicodeData.txt> <PropList.txt> <DerivedCoreProperties.txt> > internal/charprop/tables.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/mgilbir/forme/cmd/internal/ucd"
)

// categories are the values of General_Category, which are the names
// internal/charprop gives its constants. A value outside this list is a
// release this generator has not been taught, and it stops rather than
// emitting a name that does not compile — or worse, one that does.
var categories = map[string]bool{
	"Lu": true, "Ll": true, "Lt": true, "Lm": true, "Lo": true,
	"Mn": true, "Mc": true, "Me": true,
	"Nd": true, "Nl": true, "No": true,
	"Pc": true, "Pd": true, "Ps": true, "Pe": true, "Pi": true, "Pf": true, "Po": true,
	"Sm": true, "Sc": true, "Sk": true, "So": true,
	"Zs": true, "Zl": true, "Zp": true,
	"Cc": true, "Cf": true, "Cs": true, "Co": true,
}

// binary is one binary property, the file it is in, and the table it becomes.
type binary struct {
	file, property, table, doc string
}

var binaries = []binary{
	{"PropList.txt", "White_Space", "whiteSpaceRanges",
		"White_Space: the characters Unicode calls spaces, including the no-break ones and the line and paragraph separators."},
	{"PropList.txt", "Soft_Dotted", "softDottedRanges",
		"Soft_Dotted: the letters whose dot is lost when an accent is written above them."},
	{"DerivedCoreProperties.txt", "Cased", "casedRanges",
		"Cased: Lowercase, Uppercase, or General_Category Lt."},
	{"DerivedCoreProperties.txt", "Case_Ignorable", "caseIgnorableRanges",
		"Case_Ignorable: the marks, modifiers and format characters, and the punctuation Word_Break puts inside words."},
}

type span struct {
	lo, hi rune
	cat    string
}

func main() {
	version := flag.String("version", "", "the Unicode version the files came from")
	flag.Parse()
	args := flag.Args()
	if len(args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gencharprop -version <X.Y.Z> <UnicodeData.txt> "+
			"<PropList.txt> <DerivedCoreProperties.txt>")
		os.Exit(2)
	}
	if err := ucd.Check(*version, args...); err != nil {
		fail(err.Error())
	}
	chars, err := ucd.UnicodeData(args[0])
	if err != nil {
		fail(err.Error())
	}
	files := map[string]string{"PropList.txt": args[1], "DerivedCoreProperties.txt": args[2]}

	// General_Category, as runs of one category. Unassigned code points are
	// the gaps between them.
	var cats []span
	for r := rune(0); r <= 0x10FFFF; r++ {
		c, ok := chars[r]
		if !ok {
			continue
		}
		if !categories[c.Category] {
			fail(fmt.Sprintf("U+%04X has General_Category %q, which this generator does not know",
				r, c.Category))
		}
		if n := len(cats); n > 0 && cats[n-1].hi == r-1 && cats[n-1].cat == c.Category {
			cats[n-1].hi = r
			continue
		}
		cats = append(cats, span{r, r, c.Category})
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/gencharprop from Unicode's UnicodeData.txt, PropList.txt
// and DerivedCoreProperties.txt. DO NOT EDIT.

package charprop

// UnicodeVersion is the release every table in this file is read from.
const UnicodeVersion = "%s"

// General_Category. Unicode %s.
//
// %d runs of one category, sorted. A code point in none of them is unassigned,
// Cn.
var categoryRanges = [...]struct {
	lo, hi rune
	cat    Set
}{
`, *version, *version, len(cats))
	for _, s := range cats {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X, %s},\n", s.lo, s.hi, s.cat)
	}
	b.WriteString("}\n")

	for _, p := range binaries {
		spans := readProperty(files[p.file], p.property)
		fmt.Fprintf(&b, "\n// %s Unicode %s, %s.\n//\n// %d ranges.\nvar %s = [...]struct{ lo, hi rune }{\n",
			p.doc, *version, p.file, len(spans), p.table)
		for _, s := range spans {
			fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", s.lo, s.hi)
		}
		b.WriteString("}\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail("generated source does not parse: " + err.Error())
	}
	os.Stdout.Write(src)
}

// readProperty is every range a property file gives one property, merged
// where the file states adjacent runs separately. A line that names the
// property and cannot be read is a failure rather than a range left out: a
// table missing a line of its file is wrong about every character on it.
func readProperty(path, property string) []span {
	f, err := os.Open(path)
	if err != nil {
		fail(err.Error())
	}
	defer f.Close()
	var spans []span
	sc := bufio.NewScanner(f)
	for line := 1; sc.Scan(); line++ {
		text := sc.Text()
		if i := strings.IndexByte(text, '#'); i >= 0 {
			text = text[:i]
		}
		fields := strings.Split(text, ";")
		if len(fields) != 2 || strings.TrimSpace(fields[1]) != property {
			continue
		}
		lo, hi, err := parseRange(strings.TrimSpace(fields[0]))
		if err != nil {
			fail(fmt.Sprintf("%s:%d: %v", path, line, err))
		}
		spans = append(spans, span{lo: lo, hi: hi})
	}
	if err := sc.Err(); err != nil {
		fail(err.Error())
	}
	if len(spans) == 0 {
		fail(fmt.Sprintf("%s has no %s lines", path, property))
	}
	sort.Slice(spans, func(i, j int) bool { return spans[i].lo < spans[j].lo })
	merged := []span{spans[0]}
	for _, s := range spans[1:] {
		last := &merged[len(merged)-1]
		if s.lo <= last.hi {
			fail(fmt.Sprintf("%s lists U+%04X under %s twice", path, s.lo, property))
		}
		if s.lo == last.hi+1 {
			last.hi = s.hi
			continue
		}
		merged = append(merged, s)
	}
	return merged
}

func parseRange(s string) (rune, rune, error) {
	lo, hi, found := strings.Cut(s, "..")
	a, err := parseRune(lo)
	if err != nil {
		return 0, 0, err
	}
	if !found {
		return a, a, nil
	}
	b, err := parseRune(hi)
	if err != nil {
		return 0, 0, err
	}
	if b < a {
		return 0, 0, fmt.Errorf("the range %s runs backwards", s)
	}
	return a, b, nil
}

func parseRune(s string) (rune, error) {
	v, err := strconv.ParseUint(strings.TrimSpace(s), 16, 32)
	if err != nil {
		return 0, err
	}
	if v > 0x10FFFF {
		return 0, fmt.Errorf("U+%X is past the end of the code space", v)
	}
	return rune(v), nil
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "gencharprop:", msg)
	os.Exit(1)
}
