// Package cmd holds no code. This file is the one check that spans every
// generator in it, and it lives here because that is what it is about.
package cmd

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// The generators and the files they write.
//
// README says everything derived from Unicode is generated and never typed, and
// that cmd/gen* are those generators. Nine of them could not be run: they
// emitted "package fonts" into a directory whose package is "shape", or
// "package grapheme" into one whose package is "segment", and cmd/genbidi
// emitted a type and three variables under names the file it writes does not
// use. "make useable" — the one target that was wired up — overwrote
// shape/usetable.go with a file that does not compile.
//
// The committed tables reproduce byte for byte otherwise, which says what
// happened: they were generated once and then edited by hand, and the
// generators were left as they were. A generated file whose generator cannot be
// run is a typed file with a comment on it.
//
// So this is the check that could have caught it, and it needs nothing fetched:
// the package a generator emits has to be the package of the file it says it
// writes.
var generated = map[string]string{
	"genbidi":         "bidi/tables.go",
	"gencanonical":    "shape/canonical.go",
	"gencasing":       "paragraph/casingtable.go",
	"geneastasian":    "paragraph/eastasiantable.go",
	"genfullsizekana": "paragraph/kanatable.go",
	"genfullwidth":    "paragraph/widthtable.go",
	"genglyphlist":    "font/glyphnames.go",
	"genignorable":    "shape/ignorabletable.go",
	"genindic":        "shape/indiccategory.go",
	"genjoining":      "shape/joining.go",
	"genlinebreak":    "paragraph/linebreaktable.go",
	"genmatra":        "shape/indicmatra.go",
	"genscripts":      "shape/scripts.go",
	"gensegment":      "segment/tables.go",
	"genstdfonts":     "shape/standard14.go",
	"genuse":          "shape/usetable.go",
	"genvertical":     "paragraph/verticaltable.go",
	"genvowel":        "shape/indicvowel.go",
}

// emitsPackage finds the "package x" line a generator writes into its output.
// It is inside a string literal, so it is found in the source text rather than
// through the parser.
var emitsPackage = regexp.MustCompile(`(?m)^package (\w+)$`)

// TestEveryGeneratorEmitsThePackageItWritesInto is the check.
func TestEveryGeneratorEmitsThePackageItWritesInto(t *testing.T) {
	for gen, out := range generated {
		src, err := os.ReadFile(filepath.Join(gen, "main.go"))
		if err != nil {
			t.Errorf("%s: %v", gen, err)
			continue
		}
		// The first match is the generator's own package clause; the second is
		// the one it emits.
		found := emitsPackage.FindAllStringSubmatch(string(src), -1)
		if len(found) < 2 {
			t.Errorf("%s writes %s and emits no package clause", gen, out)
			continue
		}
		emits := found[1][1]
		want := packageOf(t, filepath.Join("..", out))
		if emits != want {
			t.Errorf("%s emits %q into %s, whose package is %q — the file it writes "+
				"would not compile", gen, emits, out, want)
		}
	}
}

// TestEveryGeneratorNamesTheFileItWrites keeps the usage lines honest: they are
// how anyone finds out what a generator is for, and every one of the nine named
// a directory this repository does not have.
func TestEveryGeneratorNamesTheFileItWrites(t *testing.T) {
	for gen, out := range generated {
		src, err := os.ReadFile(filepath.Join(gen, "main.go"))
		if err != nil {
			t.Errorf("%s: %v", gen, err)
			continue
		}
		if !strings.Contains(string(src), out) {
			t.Errorf("%s nowhere names %s, which is the file it writes", gen, out)
		}
	}
}

// TestEveryGeneratedFileSaysWhichGeneratorMadeIt is the other direction: a file
// that names a command nobody can run sends a reader to look for it.
func TestEveryGeneratedFileSaysWhichGeneratorMadeIt(t *testing.T) {
	for gen, out := range generated {
		src, err := os.ReadFile(filepath.Join("..", out))
		if err != nil {
			t.Errorf("%s: %v", out, err)
			continue
		}
		if !strings.Contains(string(src), "cmd/"+gen) {
			t.Errorf("%s does not say it was generated by cmd/%s", out, gen)
		}
	}
}

// packageOf is the package clause of a Go file.
func packageOf(t *testing.T, path string) string {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.PackageClauseOnly)
	if err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	return f.Name.Name
}
