// Package cmd holds no code. This file is the one check that spans every
// generator in it, and it lives here because that is what it is about.
package cmd

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/mgilbir/forme/cmd/internal/tables"
)

// The generators and the files they write.
//
// README says everything derived from Unicode is generated and never typed, and
// that cmd/gen* are those generators. Nine of them could not be run: they
// emitted "package fonts" into a directory whose package is "shape", or
// "package grapheme" into one whose package is "segment", and cmd/genbidi
// emitted a type and three variables under names the file it writes does not
// use. "make useable" — the one target that was wired up — overwrote
// shape/usetable.go with a file that does not compile.
//
// The committed tables reproduce byte for byte otherwise, which says what
// happened: they were generated once and then edited by hand, and the
// generators were left as they were. A generated file whose generator cannot be
// run is a typed file with a comment on it.
//
// So this is the check that could have caught it, and it needs nothing fetched:
// the package a generator emits has to be the package of the file it says it
// writes. The generators and their files are cmd/internal/tables.Manifest — a
// list here used to name eighteen of them and leave out the six that were not
// read from the Unicode database.

// emitsPackage finds the "package x" line a generator writes into its output.
// It is inside a string literal, so it is found in the source text rather than
// through the parser: on a line of its own in a raw literal, between two "\n"
// escapes in an interpreted one, or as the whole of one written by Fprintln.
var emitsPackage = regexp.MustCompile(`(?m)(?:^|\\n|")package (\w+)(?:$|\\n|")`)

// TestEveryGeneratorEmitsThePackageItWritesInto is the check.
func TestEveryGeneratorEmitsThePackageItWritesInto(t *testing.T) {
	for _, tb := range tables.Manifest {
		gen, out := tb.Generator, tb.Out
		src, err := os.ReadFile(filepath.Join(gen, "main.go"))
		if err != nil {
			t.Errorf("%s: %v", gen, err)
			continue
		}
		// The first match is the generator's own package clause; the second is
		// the one it emits.
		found := emitsPackage.FindAllStringSubmatch(string(src), -1)
		if len(found) < 2 {
			t.Errorf("%s writes %s and emits no package clause", gen, out)
			continue
		}
		emits := found[1][1]
		want := packageOf(t, filepath.Join("..", out))
		if emits != want {
			t.Errorf("%s emits %q into %s, whose package is %q — the file it writes "+
				"would not compile", gen, emits, out, want)
		}
	}
}

// TestEveryGeneratorNamesTheFileItWrites keeps the usage lines honest: they are
// how anyone finds out what a generator is for, and every one of the nine named
// a directory this repository does not have. A generator the manifest runs
// several times over — one per language — names the directory it writes into.
func TestEveryGeneratorNamesTheFileItWrites(t *testing.T) {
	outs := map[string][]string{}
	for _, tb := range tables.Manifest {
		outs[tb.Generator] = append(outs[tb.Generator], tb.Out)
	}
	for gen, files := range outs {
		src, err := os.ReadFile(filepath.Join(gen, "main.go"))
		if err != nil {
			t.Errorf("%s: %v", gen, err)
			continue
		}
		if len(files) == 1 {
			if !strings.Contains(string(src), files[0]) {
				t.Errorf("%s nowhere names %s, which is the file it writes", gen, files[0])
			}
			continue
		}
		for _, f := range files {
			if dir := filepath.Dir(f) + "/"; !strings.Contains(string(src), dir) {
				t.Errorf("%s writes %s and nowhere names %s", gen, f, dir)
			}
		}
	}
}

// TestEveryGeneratedFileSaysWhichGeneratorMadeIt is the other direction: a file
// that names a command nobody can run sends a reader to look for it.
func TestEveryGeneratedFileSaysWhichGeneratorMadeIt(t *testing.T) {
	for _, tb := range tables.Manifest {
		gen, out := tb.Generator, tb.Out
		src, err := os.ReadFile(filepath.Join("..", out))
		if err != nil {
			t.Errorf("%s: %v", out, err)
			continue
		}
		if !strings.Contains(string(src), "cmd/"+gen) {
			t.Errorf("%s does not say it was generated by cmd/%s", out, gen)
		}
	}
}

// packageOf is the package clause of a Go file.
func packageOf(t *testing.T, path string) string {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.PackageClauseOnly)
	if err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	return f.Name.Name
}

// TestEveryTableNamesTheReleaseTheMakefileFetches.
//
// Every generated table says which release of the database it came from, and
// three of them said "Unicode 17.0.0" because that string was typed into the
// generator: geneastasian in five places, genfullwidth and genfullsizekana in
// one each. Regenerated against a later release they would have carried the
// name of the release before it, and a provenance line that is a constant is
// worse than none — it is read as a fact.
//
// They are told now, from the Makefile's UNICODE_VERSION, which is the variable
// that decides what `make ucd` fetches; the generators whose inputs declare a
// release check the two agree. This is the other end of that: what the
// committed tables say, against what the Makefile fetches — and every table
// read from the database says it at least once.
func TestEveryTableNamesTheReleaseTheMakefileFetches(t *testing.T) {
	want := unicodeVersion(t)
	named := 0
	for _, tb := range tables.Manifest {
		if !readsTheDatabase(tb) {
			continue
		}
		gen, out := tb.Generator, tb.Out
		src, err := os.ReadFile(filepath.Join("..", out))
		if err != nil {
			t.Errorf("%s: %v", out, err)
			continue
		}
		found := unicodeVersionRe.FindAllStringSubmatch(string(src), -1)
		if len(found) == 0 {
			t.Errorf("%s is read from the Unicode database and names no release", out)
		}
		for _, m := range found {
			named++
			if m[1] != want {
				t.Errorf("%s says it is from Unicode %s and the Makefile fetches "+
					"%s; either cmd/%s has the release typed into it, or the "+
					"table was not regenerated", out, m[1], want, gen)
			}
		}
	}
	// Fifteen files name it, thirty-two times between them. A floor rather
	// than the count, so that a new table does not have to be added here — but
	// a floor all the same, because a sweep that matched nothing would pass.
	if named < 20 {
		t.Fatalf("only %d version claims were found in the generated tables; "+
			"they carry thirty-two, so this has stopped reading them", named)
	}
	t.Logf("%d version claims, all Unicode %s", named, want)
}

// unicodeVersionRe finds a release named in a generated file, in the two forms
// the generators write: a sentence, and segment's exported constant.
var unicodeVersionRe = regexp.MustCompile(
	`(?:Unicode |UnicodeVersion = ")(\d+\.\d+\.\d+)`)
