// Command genjoining generates the Arabic joining types from Unicode's own
// ArabicShaping.txt, and the transparent default from UnicodeData.txt.
//
// Joining type is what decides the shape a letter takes from its neighbours,
// and it is a property of the character rather than of any font — so it is
// Unicode's to state and not something to infer.
//
// ArabicShaping.txt does not list every character. Its header says what the
// rest are: "Those that are not explicitly listed and that are of General
// Category Mn, Me, or Cf have joining type T. All others not explicitly listed
// have joining type U." So a vowel sign written between two letters does not
// break their join, whether or not the file names it.
//
// # Two tables
//
// That default was left to the shaper, which asks package unicode — Unicode
// 15.0.0 in Go 1.26, beside a table from 17.0.0. U+0897 ARABIC PEPET, which
// Unicode 16 added as a non-spacing mark, is non-joining there: a pepet between
// two dual-joining letters breaks their join, and both take isolated or final
// forms. Seventy-five marks and format characters are in that position, and
// one, U+1171E AHOM CONSONANT SIGN MEDIAL RA, the other way round: a non-spacing
// mark in 15.0.0 and a spacing one since, so package unicode makes it
// transparent where Unicode 17.0.0 makes it non-joining.
//
// So the default is generated here, from the General_Category of the release
// the file is from, as a table of its own: defaultTransparentRanges, every
// Mn, Me and Cf character the file does not list. It is not folded into
// joiningRanges, because "the file gives this character a type" is a question
// of its own that the shaper asks — whether a character of no script of its
// own is Arabic text, for cursive letter-spacing — and a table that answered T
// for a Latin combining acute would say yes. What remains is for the shaper's
// joiningTypeOf to read this table where it now asks unicode.In, which is a
// change to the shaper and not to its data.
//
//	go run ./cmd/genjoining -version <X.Y.Z> <ArabicShaping.txt> <UnicodeData.txt> > shape/joining.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/mgilbir/forme/cmd/internal/ucd"
)

type rng struct {
	lo, hi rune
	t      string
}

func main() {
	version := flag.String("version", "", "the Unicode version the files came from")
	flag.Parse()
	args := flag.Args()
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genjoining -version <X.Y.Z> <ArabicShaping.txt> <UnicodeData.txt>")
		os.Exit(2)
	}
	if err := ucd.Check(*version, args...); err != nil {
		fail(err.Error())
	}
	f, err := os.Open(args[0])
	if err != nil {
		fail(err.Error())
	}
	defer f.Close()

	types := map[rune]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			continue
		}
		cp, err := strconv.ParseUint(strings.TrimSpace(fields[0]), 16, 32)
		if err != nil {
			continue
		}
		t := strings.TrimSpace(fields[2])
		switch t {
		case "R", "L", "D", "C", "T", "U":
			types[rune(cp)] = t
		default:
			fail(fmt.Sprintf("U+%04X has joining type %q, which is none of the six "+
				"this shaper has a branch for", cp, t))
		}
	}
	if err := sc.Err(); err != nil {
		fail(err.Error())
	}

	// The default for what the file does not list.
	chars, err := ucd.UnicodeData(args[1])
	if err != nil {
		fail(err.Error())
	}
	transparent := map[rune]string{}
	for r, c := range chars {
		if _, listed := types[r]; listed {
			continue
		}
		switch c.Category {
		case "Mn", "Me", "Cf":
			transparent[r] = "T"
		}
	}

	ranges := collapse(types)
	defaults := collapse(transparent)

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintf(w, `// Code generated by cmd/genjoining from Unicode's ArabicShaping.txt and
// UnicodeData.txt. DO NOT EDIT.

package shape

// Joining types, from Unicode %s.
//
// A cursive script writes a letter differently depending on what it joins to:
// alone, joined on the right, on the left, or on both. Which of those a letter
// can do is its joining type, and it is a property of the character — Unicode's
// to state — rather than of the font, which only supplies the four shapes.
//
// %d ranges cover every character the file gives a type for. Anything else is
// non-joining, except a non-spacing mark, an enclosing mark or a format
// character, which is transparent — see defaultTransparentRanges below: a vowel
// sign written between two letters must not break their join, and treating it
// as an ordinary character would.

type joiningRange struct {
	lo, hi rune
	t      joiningType
}

var joiningRanges = [...]joiningRange{
`, *version, len(ranges))
	for _, r := range ranges {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X, join%s},\n", r.lo, r.hi, r.t)
	}
	fmt.Fprintf(w, `}

// defaultTransparentRanges are the characters ArabicShaping.txt does not list
// and whose type is T by its own rule: every other character of General_Category
// Mn, Me or Cf in Unicode %s. %d ranges, %d characters.
//
// They are kept apart from joiningRanges because being listed is a fact of its
// own, which hasDeclaredJoiningType asks. See cmd/genjoining for why this is
// generated rather than asked of package unicode, whose release is older.
var defaultTransparentRanges = [...]struct{ lo, hi rune }{
`, *version, len(defaults), len(transparent))
	for _, r := range defaults {
		fmt.Fprintf(w, "\t{0x%04X, 0x%04X},\n", r.lo, r.hi)
	}
	fmt.Fprintln(w, "}")
}

// collapse turns a per-character map into sorted ranges of one value: the
// types run in long blocks, and a range table is a few hundred entries where
// a per-character map would be thousands.
func collapse(types map[rune]string) []rng {
	cps := make([]rune, 0, len(types))
	for r := range types {
		cps = append(cps, r)
	}
	sort.Slice(cps, func(i, j int) bool { return cps[i] < cps[j] })
	var ranges []rng
	for _, r := range cps {
		t := types[r]
		if n := len(ranges); n > 0 && ranges[n-1].t == t && ranges[n-1].hi+1 == r {
			ranges[n-1].hi = r
			continue
		}
		ranges = append(ranges, rng{r, r, t})
	}
	return ranges
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "genjoining:", msg)
	os.Exit(1)
}
