// Command genhyphen generates the hyphenation patterns css-text's
// "hyphens: auto" needs, from a hyph-utf8 pattern file.
//
// The patterns are Liang's, and so is the algorithm that reads them: a word is
// wrapped in the word-boundary marker, every substring of it is looked up, and
// the numbers the matching patterns carry are taken at their maximum at each
// position between two letters. An odd number there is a place the word may
// break. That is the whole of it, and it is why a table of five thousand
// strings is a hyphenation dictionary for a language rather than an index of
// its words.
//
// # What is taken from the file
//
// Three things, and the licence notice is one of them. The pattern files carry
// their own copyright and their own permission to redistribute "provided the
// copyright notice and this notice are preserved", so the notice is copied into
// the generated file rather than summarised: a table with the terms stripped off
// is a table nobody may ship.
//
// The other two are the \patterns{} block and the \hyphenation{} block. The
// second is not an optimisation of the first — it is the list of words the
// patterns get wrong, and a word on it takes its breaks from the list and from
// nowhere else. Some of its entries have no hyphens in them at all ("present",
// "project"), which is the list saying that a word the patterns would break must
// not be broken.
//
// The hyphenmins come from the file's own header, where a language states how
// many letters it wants left at each end of a line. They are the language's
// answer and not CSS's: hyphenate-limit-chars' initial value is "auto", which
// css-text defines as the UA's choice, and the choice a hyphenation dictionary
// ships with is the one its author made.
//
//	go run ./cmd/genhyphen <hyph-en-us.tex> > paragraph/hyphentable.go
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genhyphen <hyph-LANG.tex>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	var notice []string
	var patterns, exceptions []string
	left, right := 0, 0

	const (
		outside = iota
		inPatterns
		inExceptions
	)
	where := outside
	inLicence := false

	s := bufio.NewScanner(f)
	s.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for s.Scan() {
		line := s.Text()
		if strings.HasPrefix(line, "%") {
			text := strings.TrimSpace(strings.TrimPrefix(line, "%"))
			switch {
			case strings.HasPrefix(text, "copyright:"):
				notice = append(notice, strings.TrimSpace(strings.TrimPrefix(text, "copyright:")))
			case text == "licence:" || text == "license:":
				inLicence = true
			case inLicence && text == "text: >":
				// The block scalar's first line; its body follows.
			case inLicence && text != "" && !strings.HasSuffix(text, ":"):
				notice = append(notice, text)
			case strings.HasPrefix(text, "left:"):
				left = number(text)
				inLicence = false
			case strings.HasPrefix(text, "right:"):
				right = number(text)
				inLicence = false
			default:
				if strings.HasSuffix(text, ":") && text != "text: >" {
					inLicence = inLicence && text == "typesetting:"
				}
			}
			continue
		}
		switch {
		case strings.HasPrefix(line, `\patterns{`):
			where = inPatterns
			continue
		case strings.HasPrefix(line, `\hyphenation{`):
			where = inExceptions
			continue
		case strings.TrimSpace(line) == "}":
			where = outside
			continue
		}
		word := strings.TrimSpace(line)
		if word == "" || strings.HasPrefix(word, `\`) {
			continue
		}
		switch where {
		case inPatterns:
			patterns = append(patterns, word)
		case inExceptions:
			exceptions = append(exceptions, word)
		}
	}
	if err := s.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(patterns) == 0 {
		fmt.Fprintln(os.Stderr, "no \\patterns{} block in "+os.Args[1])
		os.Exit(1)
	}

	var b strings.Builder
	// The base name and not the path it was read from: the generated file is
	// checked in and has to say the same thing whoever ran the generator.
	fmt.Fprintf(&b, "// Code generated by cmd/genhyphen from %s.\n// DO NOT EDIT.\n\n",
		filepath.Base(os.Args[1]))
	fmt.Fprintln(&b, "package paragraph")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Hyphenation patterns for American English, from the hyph-utf8 package.")
	fmt.Fprintln(&b, "//")
	for _, line := range notice {
		fmt.Fprintln(&b, "// "+line)
	}
	fmt.Fprintln(&b, "//")
	fmt.Fprintf(&b, "// %d patterns and %d exceptions. See cmd/genhyphen for what each is\n",
		len(patterns), len(exceptions))
	fmt.Fprintln(&b, "// and hyphenate.go for the algorithm that reads them.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// enUSHyphenLeft and enUSHyphenRight are the hyphenmins the pattern file")
	fmt.Fprintln(&b, "// states for typesetting: how many letters this language wants left before the")
	fmt.Fprintln(&b, "// first break and after the last.")
	fmt.Fprintf(&b, "const (\n\tenUSHyphenLeft  = %d\n\tenUSHyphenRight = %d\n)\n\n", left, right)
	fmt.Fprintln(&b, "// enUSPatterns is Liang's \\patterns{} block, one pattern per line.")
	fmt.Fprintf(&b, "const enUSPatterns = `%s`\n\n", strings.Join(patterns, "\n"))
	fmt.Fprintln(&b, "// enUSExceptions is the \\hyphenation{} block: the words the patterns get")
	fmt.Fprintln(&b, "// wrong, each written with the breaks it is allowed and no others.")
	fmt.Fprintf(&b, "const enUSExceptions = `%s`\n", strings.Join(exceptions, "\n"))

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Stdout.Write(out)
}

// number reads the integer at the end of a "left: 2" header line.
func number(text string) int {
	i := strings.IndexByte(text, ':')
	n, err := strconv.Atoi(strings.TrimSpace(text[i+1:]))
	if err != nil {
		return 0
	}
	return n
}
