// Command genfullsizekana generates the mapping "text-transform: full-size-kana"
// asks for, from Unicode's own UnicodeData.txt.
//
// CSS Text 3 §2.1.1 says the value "converts all small Kana characters to the
// equivalent full-size Kana", and leaves it there. Unicode does enumerate them,
// though not as a property: the small kana are exactly the characters whose name
// is another character's name with "SMALL" in it.
//
//	3041;HIRAGANA LETTER SMALL A;…      ->  3042;HIRAGANA LETTER A;…
//	31F0;KATAKANA LETTER SMALL KU;…     ->  30AF;KATAKANA LETTER KU;…
//	FF67;HALFWIDTH KATAKANA LETTER SMALL A;…  ->  FF71;HALFWIDTH KATAKANA LETTER A;…
//
// Deriving it that way rather than typing the list is what makes the halfwidth
// forms and the Katakana Phonetic Extensions fall out for free, and it is what
// picks up U+1B132 and U+1B155 — the small ko Unicode 15 added in 2022, which
// the suite has a test for and which no list written before then has.
//
// Reading a character's name for its meaning is not something to do lightly, and
// it is done here because the alternative is worse and because it is checkable:
// the five full-size-kana tests in the suite between them cover hiragana,
// katakana, the phonetic extensions, the halfwidth forms and the Unicode 15
// additions, and the rule above reproduces every one of their references
// character for character.
//
// A name with SMALL in it and no full-size counterpart — U+3097 and the reserved
// positions, or a future addition — is not a mapping and is reported rather than
// guessed at.
//
//	go run ./cmd/genfullsizekana <UnicodeData.txt> > paragraph/kanatable.go
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// smallKana matches the name of a small kana and splits it where the word sits.
// Anchored at both ends: "KATAKANA LETTER SMALL KU" is one, and a name that
// merely contains the word somewhere else is not.
var smallKana = regexp.MustCompile(`^((?:HALFWIDTH )?(?:HIRAGANA|KATAKANA) LETTER )SMALL (.+)$`)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genfullsizekana <UnicodeData.txt>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type named struct {
		code rune
		name string
	}
	var all []named
	byName := map[string]rune{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for line := 1; sc.Scan(); line++ {
		fields := strings.Split(sc.Text(), ";")
		if len(fields) < 2 {
			continue
		}
		v, err := strconv.ParseUint(strings.TrimSpace(fields[0]), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "line %d: %v\n", line, err)
			os.Exit(1)
		}
		all = append(all, named{rune(v), fields[1]})
		byName[fields[1]] = rune(v)
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	type pair struct {
		from, to rune
		name     string
	}
	var pairs []pair
	for _, n := range all {
		m := smallKana.FindStringSubmatch(n.name)
		if m == nil {
			continue
		}
		full, ok := byName[m[1]+m[2]]
		if !ok {
			fmt.Fprintf(os.Stderr, "%#04X %q has no full-size counterpart\n", n.code, n.name)
			os.Exit(1)
		}
		pairs = append(pairs, pair{n.code, full, n.name})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].from < pairs[j].from })

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/genfullsizekana from Unicode's UnicodeData.txt.
// DO NOT EDIT.

package paragraph

// The full-size form of every small kana. Unicode 17.0.0.
//
// %d of them, found by their names — see cmd/genfullsizekana for why that is
// the rule and what checks it. Sorted by the character transformed. The comment
// on each row is the name of the *small* character, which is the one searched
// for.

var fullSizeKana = [...]widthPair{
`, len(pairs))
	for _, p := range pairs {
		fmt.Fprintf(&b, "\t{%#04X, %#04X}, // %s\n", p.from, p.to, p.name)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "generated source does not parse:", err)
		os.Exit(1)
	}
	os.Stdout.Write(src)
}
