// Command gendict generates the word list CSS Text §5.1's lexical line breaking
// needs, from one of ICU's break-iterator dictionaries.
//
// # Why a word list and not a rule
//
// Thai, Lao, Khmer and Burmese are written without spaces between words, and
// UAX #14 says so by giving their characters class SA — "Complex Context
// Dependent" — and then declining to say where a line may end in them. It is
// not a rule that was left out: there is no rule. Where one word ends and the
// next begins in "กรุงเทพคือสวยงาม" is a fact about the vocabulary, and the only
// way to know it is to have the vocabulary.
//
// So this is the one table in this engine that is a *language* and not a
// property of characters. Every other generated table here is Unicode's
// statement about code points; this is a list of the words a language has.
//
// # Where it comes from and what travels with it
//
// ICU's break-iterator dictionaries, which are what every browser segments
// these scripts with — so a page laid out from them breaks where a reader of
// the suite's references expects. They are plain word lists, one word per line,
// with a header of comments.
//
// The header is a licence and it is copied into the generated file rather than
// summarised. The Unicode licence permits redistribution "provided that either
// (a) this copyright and permission notice appear with all copies of the Data
// Files, or (b) this copyright and permission notice appear in associated
// Documentation" — a table with the terms stripped off is a table nobody may
// ship, and the Thai list carries a second notice from its own authors besides.
//
//	go run ./cmd/gendict thai <thaidict.txt> > paragraph/thaidict.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode/utf8"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gendict <name> <dictionary.txt>")
		os.Exit(2)
	}
	name := os.Args[1]
	f, err := os.Open(os.Args[2])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	var notice []string
	var words []string
	seen := map[string]bool{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		line := strings.TrimPrefix(sc.Text(), "\ufeff")
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			// The header, which is the licence. It is kept exactly as it
			// stands, comment marker and all.
			notice = append(notice, strings.TrimRight(line, " \t"))
			continue
		}
		if trimmed == "" {
			continue
		}
		// Some entries carry a tab-separated weight the segmentation here does
		// not read. The word is the first field.
		word := strings.TrimSpace(strings.SplitN(trimmed, "\t", 2)[0])
		if word == "" || strings.ContainsAny(word, "`\r\n") {
			// A backquote could not go in the raw literal below, and no
			// dictionary has one. Refusing rather than escaping keeps the
			// generated file readable and the check against the source exact.
			continue
		}
		if seen[word] {
			continue
		}
		seen[word] = true
		words = append(words, word)
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(words) == 0 {
		fmt.Fprintln(os.Stderr, "gendict: no words in the file")
		os.Exit(1)
	}
	sort.Strings(words)

	longest := 0
	for _, w := range words {
		if n := utf8.RuneCountInString(w); n > longest {
			longest = n
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/gendict from ICU's %s.\n// DO NOT EDIT.\n\npackage paragraph\n\n",
		os.Args[2][strings.LastIndexByte(os.Args[2], '/')+1:])
	fmt.Fprintf(&b, "// The licence the word list is under, copied from its own header. See\n"+
		"// cmd/gendict for why it is here in full rather than summarised.\n//\n")
	for _, line := range notice {
		if line == "" {
			fmt.Fprintln(&b, "//")
			continue
		}
		fmt.Fprintf(&b, "// %s\n", line)
	}
	fmt.Fprintf(&b, `
// %sWords is the dictionary, one word per line and sorted.
//
// %d words, the longest %d characters. Sorted so that the file can be compared
// with the one it came from, and so that a reader looking for a word can find
// it; nothing about the lookup depends on the order.
const %sWords = `+"`"+`
`, name, len(words), longest, name)
	for _, w := range words {
		b.WriteString(w)
		b.WriteByte('\n')
	}
	fmt.Fprintf(&b, "`"+`

// %sLongestWord bounds the search at each position: no word is longer, so a
// probe that has read this many characters without finding one has finished.
const %sLongestWord = %d
`, name, name, longest)
	fmt.Print(b.String())
}
