// Command genbrotli generates the two tables a Brotli decoder cannot compute:
// the context lookup table and the static dictionary's word transforms.
//
// Both are stated by RFC 7932 and are the same for every stream, so they are
// read from the reference implementation's own source rather than transcribed.
// Transcribing them was the alternative and is how a decoder acquires a bug it
// cannot find: a wrong entry in either table corrupts one output in a thousand,
// at a position that depends on the input.
//
// The static dictionary itself is not here. It is 122,784 bytes of text, and a
// Go source file holding it as a literal would be half a megabyte that no one
// can read; it is embedded from dictionary.bin beside the package, with a test
// that checks its length and digest.
//
//	go run ./cmd/genbrotli <context.c> <transform.c> > brotli/tables.go
package main

import (
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: genbrotli <context.c> <transform.c>")
		os.Exit(2)
	}
	contexts := readContextTable(mustRead(os.Args[1]))
	prefixes, kinds, suffixes := readTransforms(mustRead(os.Args[2]))

	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by cmd/genbrotli from the reference Brotli's")
	fmt.Fprintln(&b, "// c/common/context.c and c/common/transform.c. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package brotli")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// contextLookup is RFC 7932 §7's four context models, 512 bytes each: the")
	fmt.Fprintln(&b, "// first 256 entries of a model are indexed by the byte before the one being")
	fmt.Fprintln(&b, "// decoded and the second 256 by the byte before that, and the context is the")
	fmt.Fprintln(&b, "// two OR'd together.")
	fmt.Fprintln(&b, "var contextLookup = [2048]byte{")
	for i := 0; i < len(contexts); i += 16 {
		fmt.Fprint(&b, "\t")
		for j := i; j < i+16 && j < len(contexts); j++ {
			fmt.Fprintf(&b, "%d, ", contexts[j])
		}
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// transforms is RFC 7932 §8's list, resolved: each entry is the text put")
	fmt.Fprintln(&b, "// before a dictionary word, what is done to the word itself, and the text put")
	fmt.Fprintln(&b, "// after it. A dictionary reference names a word and one of these.")
	fmt.Fprintln(&b, "var transforms = [...]transform{")
	for i := range kinds {
		fmt.Fprintf(&b, "\t{%q, %d, %q},\n", prefixes[i], kinds[i], suffixes[i])
	}
	fmt.Fprintln(&b, "}")

	// Through gofmt, so that re-running this over the same sources produces
	// the same file byte for byte and a stale generated table is a diff.
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fail("the generated source does not parse: " + err.Error())
	}
	os.Stdout.Write(out)
}

func mustRead(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	return string(data)
}

var numbers = regexp.MustCompile(`\d+`)

// readContextTable pulls the 2048 bytes out of the one array context.c holds.
func readContextTable(src string) []byte {
	start := strings.Index(src, "_kBrotliContextLookupTable[2048] = {")
	if start < 0 {
		fail("context.c has no _kBrotliContextLookupTable[2048]")
	}
	body := src[start:]
	body = body[strings.Index(body, "{")+1:]
	body = body[:strings.Index(body, "};")]
	// The comments between the four models name them and hold no digits, but a
	// stray one would be read as data, so they are cut rather than trusted.
	body = stripComments(body)
	var out []byte
	for _, m := range numbers.FindAllString(body, -1) {
		v, err := strconv.Atoi(m)
		if err != nil || v > 255 {
			fail("context.c holds " + m + ", which is not a byte")
		}
		out = append(out, byte(v))
	}
	if len(out) != 2048 {
		fail(fmt.Sprintf("context.c gave %d bytes, want 2048", len(out)))
	}
	return out
}

// readTransforms resolves kTransformsData against the pascal-style strings
// kPrefixSuffix holds and kPrefixSuffixMap indexes.
func readTransforms(src string) (prefixes []string, kinds []int, suffixes []string) {
	// The declaration is [217] and the literal holds 216 bytes: the last one is
	// C's implicit terminator, and kPrefixSuffixMap's final entry points at it
	// to name the empty prefix. Leaving it off makes that entry run off the end.
	blob := cString(src, "kPrefixSuffix[217] =") + "\x00"
	offsets := cNumbers(src, "kPrefixSuffixMap[50] = {")
	data := cNumbers(src, "kTransformsData[] = {")

	word := func(id int) string {
		if id >= len(offsets) {
			fail(fmt.Sprintf("transform names prefix %d of %d", id, len(offsets)))
		}
		at := offsets[id]
		if at >= len(blob) {
			fail("prefix offset past the blob")
		}
		// Pascal-style: a length byte, then that many bytes.
		n := int(blob[at])
		if at+1+n > len(blob) {
			fail("prefix runs past the blob")
		}
		return blob[at+1 : at+1+n]
	}
	if len(data)%3 != 0 {
		fail("kTransformsData is not a whole number of triples")
	}
	for i := 0; i < len(data); i += 3 {
		prefixes = append(prefixes, word(data[i]))
		kinds = append(kinds, data[i+1])
		suffixes = append(suffixes, word(data[i+2]))
	}
	if len(kinds) != 121 {
		fail(fmt.Sprintf("%d transforms, and RFC 7932 states 121", len(kinds)))
	}
	return prefixes, kinds, suffixes
}

// cNumbers reads the decimal and hexadecimal literals of one C array.
func cNumbers(src, marker string) []int {
	start := strings.Index(src, marker)
	if start < 0 {
		fail("transform.c has no " + marker)
	}
	body := src[start+len(marker):]
	body = body[:strings.Index(body, "};")]
	body = stripComments(body)
	var out []int
	for _, tok := range strings.FieldsFunc(body, func(r rune) bool {
		return r == ',' || r == ' ' || r == '\n' || r == '\t' || r == '\r'
	}) {
		tok = strings.TrimSpace(tok)
		if tok == "" {
			continue
		}
		if strings.HasPrefix(tok, "BROTLI_TRANSFORM_") {
			out = append(out, transformKind(tok))
			continue
		}
		v, err := strconv.ParseInt(strings.TrimPrefix(strings.TrimPrefix(tok, "0x"), "0X"), base(tok), 32)
		if err != nil {
			fail("transform.c holds " + tok + ", which is not a number")
		}
		out = append(out, int(v))
	}
	return out
}

func base(tok string) int {
	if strings.HasPrefix(tok, "0x") || strings.HasPrefix(tok, "0X") {
		return 16
	}
	return 10
}

// transformKind maps the reference's names to RFC 7932 §8's numbering, which is
// the numbering the names are declared in.
var transformNames = []string{
	"IDENTITY", "OMIT_LAST_1", "OMIT_LAST_2", "OMIT_LAST_3", "OMIT_LAST_4",
	"OMIT_LAST_5", "OMIT_LAST_6", "OMIT_LAST_7", "OMIT_LAST_8", "OMIT_LAST_9",
	"UPPERCASE_FIRST", "UPPERCASE_ALL", "OMIT_FIRST_1", "OMIT_FIRST_2",
	"OMIT_FIRST_3", "OMIT_FIRST_4", "OMIT_FIRST_5", "OMIT_FIRST_6",
	"OMIT_FIRST_7", "OMIT_FIRST_8", "OMIT_FIRST_9", "SHIFT_FIRST", "SHIFT_ALL",
}

func transformKind(tok string) int {
	name := strings.TrimPrefix(tok, "BROTLI_TRANSFORM_")
	for i, want := range transformNames {
		if name == want {
			return i
		}
	}
	fail("unknown transform " + tok)
	return 0
}

// cString joins and unescapes the C string literal a marker introduces.
func cString(src, marker string) string {
	start := strings.Index(src, marker)
	if start < 0 {
		fail("transform.c has no " + marker)
	}
	body := src[start+len(marker):]
	body = body[:strings.Index(body, ";")]
	body = stripComments(body)

	var out strings.Builder
	for {
		open := strings.Index(body, `"`)
		if open < 0 {
			break
		}
		body = body[open+1:]
		// The closing quote is the first one not escaped.
		end := 0
		for end < len(body) {
			if body[end] == '\\' {
				end += 2
				continue
			}
			if body[end] == '"' {
				break
			}
			end++
		}
		out.WriteString(unescape(body[:end]))
		body = body[end+1:]
	}
	return out.String()
}

// unescape reads C's escapes: the octal ones the lengths are written as, the
// hexadecimal ones the non-breaking space is written as, and the quotes.
func unescape(s string) string {
	var out strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] != '\\' {
			out.WriteByte(s[i])
			continue
		}
		i++
		if i >= len(s) {
			fail("a trailing backslash")
		}
		switch c := s[i]; {
		case c >= '0' && c <= '7':
			v := 0
			for n := 0; n < 3 && i < len(s) && s[i] >= '0' && s[i] <= '7'; n++ {
				v = v*8 + int(s[i]-'0')
				i++
			}
			i--
			out.WriteByte(byte(v))
		case c == 'x':
			v, err := strconv.ParseInt(s[i+1:i+3], 16, 32)
			if err != nil {
				fail("a bad hexadecimal escape")
			}
			out.WriteByte(byte(v))
			i += 2
		case c == 'n':
			out.WriteByte('\n')
		case c == 't':
			out.WriteByte('\t')
		case c == 'r':
			out.WriteByte('\r')
		case c == '\\', c == '"', c == '\'':
			out.WriteByte(c)
		default:
			fail("an escape this does not read: \\" + string(c))
		}
	}
	return out.String()
}

// stripComments removes C comments, which in these files carry column markers
// full of digits.
func stripComments(s string) string {
	var out strings.Builder
	for {
		open := strings.Index(s, "/*")
		if open < 0 {
			out.WriteString(s)
			return out.String()
		}
		out.WriteString(s[:open])
		s = s[open+2:]
		end := strings.Index(s, "*/")
		if end < 0 {
			return out.String()
		}
		s = s[end+2:]
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "genbrotli: "+msg)
	os.Exit(1)
}
