#!/bin/sh
# Runs two decoders other than this module's over the WOFF 2 collection
# variants beside this file, which font/woff2variants_test.go builds — with
# WOFF2_VARIANTS=write, from tables lifted from the collections one directory
# up — and records what each made of them, for that test to hold DecodeWOFF2
# to:
#
#   sh make.sh WOFF2_BUILD_DIR ALLSORTS_HARNESS
#
# google.txt is google/woff2's decoder, woff2_decompress from WOFF2_BUILD_DIR,
# built as ../make.py says (google/woff2 at
# fb9c3379f2605b10f3e8f1d9636664ab5576775c, against brotli 1.2.0): for each
# variant, "refused" and what it said, or each face it rebuilt and the SHA-256 of each of its
# tables, head's with its checkSumAdjustment cleared.
#
# allsorts.txt is allsorts 0.17.0 (YesLogic, https://crates.io/crates/allsorts),
# whose WOFF 2 reader shares no code with google/woff2's: for each variant,
# each face as allsorts rebuilds it, every table in hex, a space in a tag
# written as _. ALLSORTS_HARNESS is a program built against it, from
# allsorts-harness.rs beside this file, with a Cargo.toml naming
# allsorts = "=0.17.0".
set -e
here=$(cd "$(dirname "$0")" && pwd)
build=$1
harness=$2
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

{
  echo "# Generated by make.sh with google/woff2 at fb9c3379f2605b10f3e8f1d9636664ab5576775c. DO NOT EDIT."
  for f in "$here"/*.woff2; do
    name=$(basename "$f")
    echo "file $name"
    cp "$f" "$tmp/$name"
    if said=$("$build/woff2_decompress" "$tmp/$name" 2>&1) && [ -s "$tmp/${name%.woff2}.ttf" ]; then
      python3 - "$tmp/${name%.woff2}.ttf" <<'EOF'
import hashlib, struct, sys
data = open(sys.argv[1], "rb").read()
assert data[:4] == b"ttcf"
n = struct.unpack(">I", data[8:12])[0]
for i in range(n):
    at = struct.unpack(">I", data[12 + 4 * i:16 + 4 * i])[0]
    count = struct.unpack(">H", data[at + 4:at + 6])[0]
    print(f"font {i} tables {count}")
    for k in range(count):
        rec = at + 12 + 16 * k
        tag = data[rec:rec + 4].decode("latin-1")
        off, length = struct.unpack(">II", data[rec + 8:rec + 16])
        table = bytearray(data[off:off + length])
        if tag == "head":
            table[8:12] = b"\0\0\0\0"
        print(f"table {tag.replace(' ', '_')} {hashlib.sha256(table).hexdigest()}")
EOF
    else
      echo "refused $(echo "$said" | tr '\n' ' ')"
    fi
  done
} > "$here/google.txt"

{
  echo "# Generated by make.sh with allsorts 0.17.0. DO NOT EDIT."
  "$harness" "$here"/*.woff2
} > "$here/allsorts.txt"
