# Writes the outline points FreeType loads for every glyph of CFF and CFF2
# faces, so that shape/cffpoints_test.go can hold the points kerx attaches by
# (shape/kerx.go, cffContourPoints) to them, and aatpos.py can hand them to
# HarfBuzz in place of FreeType:
#
#   make ftpoints
#
# The points are FreeType's for an unscaled, unhinted load (FT_LOAD_NO_SCALE |
# FT_LOAD_NO_HINTING), in font units: what HarfBuzz over FreeType hands a
# kerx table asking for a glyph's points, hb_ft_get_glyph_contour_point, at a
# font scaled to its units per em. points.c beside this reads them, compiled
# against the FreeType pkg-config names; the version it ran is recorded, and
# the expectations are committed, as every oracle's are, so the tests need no
# FreeType of their own.
#
# Each face is named on the command line as NAME=PATH, with @AXIS=VALUE,...
# for a design-space location; and #hash to record each glyph's points as the
# start of their SHA-256 rather than whole, for faces of thousands of glyphs,
# or #every=N to record every Nth glyph's whole and no other.
# A face whose file is not here — a corpus not fetched — is left out.
import hashlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
out_path = sys.argv[1]


def build():
    exe = os.path.join(tempfile.mkdtemp(), "points")
    flags = subprocess.run(["pkg-config", "--cflags", "--libs", "freetype2"], check=True,
                           capture_output=True, text=True).stdout.split()
    subprocess.run(["cc", "-O1", "-o", exe, os.path.join(HERE, "points.c")] + flags, check=True)
    return exe


exe = build()
out, version = [], None
for arg in sys.argv[2:]:
    name, rest = arg.split("=", 1)
    hashed = rest.endswith("#hash")
    rest = rest.removesuffix("#hash")
    every = 1
    if "#every=" in rest:
        rest, n = rest.split("#every=")
        every = int(n)
    path, _, location = rest.partition("@")
    if not os.path.exists(path):
        print(f"{name}: {path} is not here; left out", file=sys.stderr)
        continue
    axes = [a for a in location.split(",") if a]
    lines = subprocess.run([exe, path] + axes, check=True, capture_output=True,
                           text=True).stdout.splitlines()
    version = lines[0]
    digest = hashlib.sha256(open(path, "rb").read()).hexdigest()
    kind = "hash" if hashed else "full" if every == 1 else f"every={every}"
    out.append(f"face {name} {digest} {','.join(axes) or '-'} {kind}")
    for line in lines[1:]:
        gid, points = line[2:].split(" ", 1) if " " in line[2:] else (line[2:], "")
        if int(gid) % every:
            continue
        if hashed:
            # Each point as x,y alone: the tags say only which are control
            # points, which a point attached by needs no knowing.
            text = " ".join(p.rsplit(",", 1)[0] for p in points.split()) if points != "none" else "none"
            out.append(f"H {gid} {hashlib.sha256(text.encode()).hexdigest()[:16]}")
        else:
            out.append(f"G {gid} {points}".rstrip())

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/freetype/points.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, its SHA-256, the location it was loaded at (- for its\n")
    w.write("# default), and each glyph's outline points as FreeType loads them\n")
    w.write("# unscaled and unhinted: G and the points as x,y,tag (1 on the curve,\n")
    w.write("# 2 a cubic control point), or none; or H and the start of the SHA-256\n")
    w.write("# of the points as x,y separated by spaces.\n")
    w.write(f"# {version}\n")
    for line in out:
        w.write(line + "\n")
