# Writes every glyph of every bitmap strike of the faces named, as FreeType
# loads it, so that shape/strikes_test.go can hold what Face.PaintGlyph paints
# from EBLC and EBDT, and from Apple's bloc and bdat, to it:
#
#   make ftstrikes
#
# HarfBuzz reads no monochrome or greyscale strikes, so FreeType is the
# oracle: strikes.c beside this selects each strike in turn (FT_Select_Size)
# and loads each glyph's bitmap, compiled against the FreeType pkg-config
# names. The version it ran is recorded, and the expectations are committed,
# as every oracle's are, so the tests need no FreeType of their own.
#
# Each face is named on the command line as NAME=PATH. A face whose file is
# not here is left out.
import hashlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
out_path = sys.argv[1]


def build():
    exe = os.path.join(tempfile.mkdtemp(), "strikes")
    flags = subprocess.run(["pkg-config", "--cflags", "--libs", "freetype2"], check=True,
                           capture_output=True, text=True).stdout.split()
    subprocess.run(["cc", "-O1", "-o", exe, os.path.join(HERE, "strikes.c")] + flags, check=True)
    return exe


exe = build()
out, version = [], None
for arg in sys.argv[2:]:
    name, path = arg.split("=", 1)
    if not os.path.exists(path):
        print(f"{name}: {path} is not here; left out", file=sys.stderr)
        continue
    lines = subprocess.run([exe, path], check=True, capture_output=True, text=True).stdout.splitlines()
    version = lines[0]
    digest = hashlib.sha256(open(path, "rb").read()).hexdigest()
    out.append(f"face {name} {digest}")
    out.extend(lines[1:])

with open(out_path, "w", encoding="utf-8") as w:
    w.write("# Generated by testdata/freetype/strikes.py. DO NOT EDIT.\n")
    w.write("#\n")
    w.write("# For each face, its SHA-256; for each of its strikes, S, its index and\n")
    w.write("# its ppem across and down; and for each glyph G, its index, and either\n")
    w.write("# none or the bitmap FreeType loads: its bit depth, width, rows, left and\n")
    w.write("# top, and then each row's samples, from 0 to 2^depth-1 in hexadecimal.\n")
    w.write(f"# {version}\n")
    for line in out:
        w.write(line + "\n")
